- README.md
- chain/subnet_evm.go
- params/config.go
- plugin/evm/block_verification.go
- plugin/evm/config.go
- plugin/evm/vm.go
This PR adds a mechanism to redirect fees to addresses instead of burning them by sending to a blackhole address
Adds`allowRedirectFees` bool flag to genesis chain configs.
Adds a configurable `coinbase` address to chain configs. 
Block builders can specify their `coinbase` addresses to collect fees if chain activates `allowRedirectFees` in the genesis.
> add allowfeerecipients in genesis & add coinbase to chain config

- core/vm/contracts.go
- core/vm/contracts_stateful.go
- core/vm/evm.go
- rpc/websocket_test.go
This PR adds the framework for stateful precompiles. This framework is borrowed from coreth and enables us to start building more powerful types of precompiles within the subnet-evm.
> [AV-1297] Add framework for stateful precompiles

- chain/subnet_evm.go
- constants/constants.go
- core/vm/errors.go
- core/vm/evm.go
- plugin/evm/block_verification.go
- plugin/evm/vm.go
This PR adds a few small nits and fixes a small bug in the tests.
> Prevent prohibited addresses nits

- README.md
- core/genesis_test.go
- core/stateful_precompile_test.go
- core/test_blockchain.go
- core/vm/evm.go
- params/config.go
- plugin/evm/vm_test.go
- precompile/allow_list.go
- precompile/contract_deployer_allow_list.go
- precompile/params.go
This PR separates the allow list into a module that can be easily used to implement future types of allow lists to restrict resources. It then moves the contract deployer allow list to a separate file that relies on this module.
> Abstract allow list and separate contract allow list

- .github/workflows/lint-and-tests.yml
- accounts/keystore/account_cache_test.go
- plugin/evm/tx_gossiping_test.go
- rpc/websocket_test.go
- scripts/build_test.sh
- scripts/coverage.sh
This PR marks a few identified flaky tests as flaky so we can skip over them until we can fix them.
Additionally, this adds a coverage.sh script from coreth and modifies the build_test.sh script to take in arbitrary arguments. This is a change from coreth that's used to pass in different arguments when running on different OSs so that we do not need to run with race detection enabled on multiple GH Actions and to optimize the runtime.
> Ci improvements

- README.md
This PR adds a blurb to the README which states what uint256 values correspond to the possible allow list roles.
> Add uint256 role blurb on allow list to readme

- precompile/contract.go
- precompile/stateful_precompile_config.go
This PR sets the code of stateful precompiles when they are configured to 0x00. This ensures that the precompile will pass the check to ensure that there is a non-zero length contract at the called address when Solidity makes a call to another contract.
> Set precompile code

- accounts/keystore/keystore_test.go
- core/blockchain.go
This PR moves the shutdown manager stop above the other functionality when stopping the blockchain to ensure that the last trie is written as early as possible and reduce the likelihood that state will need to be regenerated on a restart.
> Improve stop flow to reduce frequency of unclean shutdowns

- plugin/evm/vm.go
Adds chain prefixes and source location to logs, through custom log formatting. 
An example output (from `CTfG5uAYxZhABKoqVHPgTRQF1RbHSbkc1LygbDYyycUD765qB.log`)
```
{"@level":"debug","@message":"plugin address","@timestamp":"2022-04-07T22:09:16.334408+03:00","address":"/var/folders/qx/3vldh17n7_n2l8fd5ysyr7bw0000gn/T/plugin2351922550","network":"unix"}
{"@level":"trace","@message":"plugin received interrupt signal, ignoring","@timestamp":"2022-04-07T22:10:12.522463+03:00","count":1}
{"@level":"debug","@message":"plugin address","@timestamp":"2022-04-07T22:10:52.801265+03:00","address":"/var/folders/qx/3vldh17n7_n2l8fd5ysyr7bw0000gn/T/plugin1845823026","network":"unix"}
INFO [04-07|22:10:52.802] Initializing Subnet EVM VM …
```
> AV-1463: add custom log format for chain prefix and source location

- Dockerfile
- scripts/build.sh
This PR bumps the minimum go version in the build script and Dockerfile v1.17.9. These do not exist yet, so this is in anticipation of v1.17.9 being released today.
> Go min v1.17.9

- plugin/evm/vm.go
> [AV-1596] Add priority regossip addresses to locals

- .markdownlint.json
- README.md
Updates to `README.md` per [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint).
Markdownlint is configured via `.markdownlint.json`. The following 3 rules were added to `.markdownlint.json` since I was unable to remove/change them in `README.md`.
* [MD041 - First line in a file should be a top-level heading](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md041)
* [MD013 - Line length](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#MD013)
* [MD033 - Inline HTML](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#MD033)
The actual changes to `README.md` are related to the following markdownlint rules
* [MD040 - Fenced code blocks should have a language …
> Updates to `README.md` per markdownlint

- params/config.go
This PR adds comments to the FeeConfig struct.
> Add comments to FeeConfig

- README.md
With https://github.com/ava-labs/avalanche-docs/pull/819, the doc https://docs.avax.network/subnets/create-a-local-subnet will focus on using avalanche-cli. We need to put back the contents of using subnet-evm on a local network here.
> add back using Subnet-evm to create a local network

- scripts/build.sh
- scripts/constants.sh
Testing:
Current branch head: 
```
➜  subnet-evm git:(remove-git-build-script) ./scripts/build.sh
Using branch: remove-git-build-script
Building Subnet EVM Version: v0.2.5; GitCommit: 84508375452a3330ce1e7754e07a2c036125d868 at /Users/joshua.kim/go/src/github.com/ava-labs/avalanchego/build/plugins/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy
```
Then setup a dummy repository with not git info like so: `cp -r subnet-evm /tmp && cd /tmp/subnet-evm`
Output:
```
➜  subnet-evm ./scripts/build.sh
Using branch: unknown
Building Subnet EVM Version: v0.2.5; GitCommit: unknown at /Users/joshua.kim/go/src/github.com/ava-labs/avalanchego/build/plugins/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy
```
> Using a placeholder if we're not able to find Git commit info in build script

- tests/e2e/runner/runner.go
Part of E2E code that calls ANR Health() function. If the error is nil, then the field ClusterInfo of the return value, will not be nil.
> [AV-1895] remove useless check for nil clusterInfo

- params/precompile_config.go
- params/precompile_config_test.go
Additional verification on upgradeBytes (enforce monotonically increasing timestamps across different keys)
> upgradeBytes: verify increasing timestamps accross keys

- params/config.go
Convert NetworkUpgrades, PrecompileUpgrade, and UpgradeConfig to json for including in the .String() representation.
> convert nested configs to json in String()

- README.md
- scripts/versions.sh
This PR starts the release cycle for v0.2.9.
- Bumps scripts/versions.sh version to v0.2.9
- Updates AvalancheGo compatibility in README (is there a better way to do this?)
> Start v0.2.9 release cycle

- .github/workflows/lint-tests-release.yml
- Dockerfile
- README.md
- accounts/abi/bind/bind_test.go
- cmd/simulator/go.mod
- go.mod
- scripts/build.sh
- scripts/parser/go.mod
This PR bumps the minimum golang version for building subnet-evm to v1.18.1.
> Bump go version to 1.18

- core/genesis_test.go
- core/stateful_precompile_test.go
`assertState` can throw panic if no such function is defined in tests. This PR fixes this behavior by adding a nil check
> fix nil assert state functions panic in test

- go.mod
- go.sum
- tests/e2e/runner/runner.go
This PR bumps the ANR version to depend on AGO bump PR merged to master: ee59fae043fce29093e29a7967ca97d7283db9af and cleans up the logger as per comments from @felipemadero .
> Clean up logger and use commit from PR

- plugin/evm/log.go
This PR adds a small comment to state that a suspicious line will not cause an index out of bounds because the arguments will be normalized in advance.
> Add comment to clarify log line won't index out of bounds

- internal/ethapi/api.go
- params/precompile_config.go
Adds 2 API requests
Returns chain config with upgrades. Takes no parameters.
Reques:
```
{
"jsonrpc": "2.0",
"method": "eth_getChainConfig",
"params": [],
"id": 1
}
```
Response:
```
{
"jsonrpc": "2.0",
"id": 1,
"result": {
"chainId": 43214,
"feeConfig": {
"gasLimit": 8000000,
"targetBlockRate": 2,
"minBaseFee": 33000000000,
"targetGas": 15000000,
"baseFeeChangeDenominator": 36,
"minBlockGasCost": 0,
"maxBlockGasCost": 1000000,
"blockGasCostStep": 200000
},
"allowFeeRecipients": true,
"homesteadBlock": 0,
"eip150Block": 0,
"eip150Hash": "0x2086799aeebeae135c246c65021c82b4e15a2c451340993aacfd2751886514f0",
"eip155Block": 0,
"eip158Block": 0,
"byzantiumBlock": 0,
"constantinopleBlock": 0,
"petersburgBlock": 0,
"istanbulBlock": 0,
"muirGlacierBlock": 0,
"subnetEVMTimestamp": 0, …
```
> Add get chain config api

- plugin/evm/vm.go
This PR updates GetBlockIDAtHeight to return the correct error expected by the engine's interface.
This was causing an issue where nodes that have state synced would not be able to parse some ancestors during bootstrapping.
> GetBlockIDAtHeight: return database.ErrNotFound

- precompile/config_test.go
- precompile/contract_native_minter.go
- precompile/fee_config_manager.go
This PR updates two error messages to a formatted error including the relevant address to make fixing the error easier for users.
> precompile: add formatted errors to precompile verify

- cmd/simulator/go.mod
- cmd/simulator/go.sum
- go.mod
- go.sum
- scripts/versions.sh
Bump avalanchego to v1.9.0 and avalanche-network-runner to master branch at commit: https://github.com/ava-labs/avalanche-network-runner/commit/e7eb33c1e830e6be0a39162ebf4a3abee80a335b
Resolves #289
> Update avalanchego v1.9.0

- .github/workflows/lint-tests-release.yml
Goreleaser failing on real releases. there is a check for the git repositoty to not being dirty, and  that seems to only be checked when doing the release, not when doing snapshots. That's why it was not seen before.
The repo was dirty because osxcross was inside it. this PR sets osxcross and subnet-evm side by side.
> fix goreleaser problem from v0.4.0 

- .github/workflows/lint-tests-release.yml
Adds dependencies required for cross-compiling MacOS build with reference to required dependencies here: https://tenbaht.github.io/sduino/developer/cross-compile-for-osx/
> add more osxcross dependencies

- scripts/versions.sh
This PR bumps the version to v0.4.2 to start the next release cycle.
> Bump version to v0.4.2

- core/blockchain.go
- core/state/state_object.go
- utils/metered_cache.go
This PR adds a lock prior to calling `Flatten` on the snapshot in the async acceptor queue to fix an issue where the snapshot may be marked as stale while we are processing a block.
If the disk snapshot is marked as stale, it can result in the processing block falling back to read from the trie instead of the snapshot during block execution and result in a significant slowdown.
> Block Acceptor from Flattening during Verification

- scripts/run.sh
Added ability to specify the exact e2e test we want to run in the run script 
Example: 
```ENABLE_SOLIDITY_TESTS=true GINKGO_FOCUS_FLAGS="fee manager" ./scripts/run.sh```
> Specify E2E Tests in Run Script

- core/blockchain.go
This PR adds a metric for the number of verified transactions in the same style that we track processed and accepted gas.
This PR adds an additional global metric for processed transactions next to accepted transactions and increments it when we finish inserting a block.
> Add counter for verified transactions

- go.mod
- go.sum
- precompile/utils_test.go
Generally we import the assert functionality of the stretchr package, keeps the code more consistent.
CI tests
> nit: remove gotest.tools dependency

- core/state/statedb.go
- core/state/statedb_test.go
- core/vm/instructions.go
- core/vm/interface.go
- precompile/contract.go
This PR updates the function signature of statedb `AddLog(...)` function to:
```
AddLog(addr common.Address, topics []common.Hash, data []byte, blockNumber uint64)
```
Previously, a fully formed log was passed directly in with only these params populated. This PR is intended to avoid needing to import `core/types/` package into the `precompile/` package which currently creates a circular import.
This is intended as a no-op change, so no unit tests were added.
> Update AddLog function signature to support usage from precompiles

- .github/CODEOWNERS
- accounts/abi/abi.go
- accounts/abi/abi_test.go
- accounts/abi/topics.go
This PR adds `PackTopics` to the abi package to support packing events. This is intended to be made available for precompiles to pack events, so that they can create logs.
This works by using the existing code for packing topics used in the abi package to support creating filter queries and breaks out the actual creation of a topic hash into a helper function, so that we can re-purpose it to create an array of topics as would be created by an event log rather than the type `[][]common.Hash` that would be used when creating a filter query.
Adds a unit test in `abi_test.go` to test the encoding of an event without indexed args, with indexed args, and of an anonymous event.
https://docs.soliditylang.org/en/v0.8.17/abi-spec.html#indexed-event-encoding
> Pack topics

- core/stateful_precompile_test.go
- core/vm/evm.go
- precompile/contract.go
This PR adds a method `CallFromPrecompile` to the interface PrecompileAccessibleState.
- CallFromPrecompile creates an `AccountRef`, which implements ContractRef, then invokes `Call` for the contract
> Add CallFromPrecompile to PrecompileAccessibleState

- accounts/abi/bind/backends/simulated.go
- eth/api_backend.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/filters/filter.go
- eth/filters/filter_system.go
- eth/filters/filter_system_test.go
- plugin/evm/config.go
- plugin/evm/vm.go
This PR separates the `indexed` and `unindexed` block log caches. We do this because we want the storage of indexed logs to evict unindexed logs (which are much more important to keep in memory for low RPC latency).
When serving `eth_getLogs` requests, the node may iterate over any number of blocks looking for events. It significantly improves performance to keep these blocks in memory and separated between indexed/unindexed logs (requires iteration of all unindexed logs for each request).
> Improved eth_getLogs caching

- .github/workflows/lint-tests-release.yml
Update on ubuntu-latest on CI left dependency inconsistencies that produce failure when trying to install gcc arm compiler. An update of dependencies with apt-get update fix the situation and may be a good add on to the CI to prevent future failures with simular eason.
> apt-get update to try to fix this

- cmd/simulator/go.mod
- cmd/simulator/go.sum
- go.mod
- go.sum
- scripts/versions.sh
This PR bumps avalanchego dependency to v1.9.4
> Bump avalanchego to v1.9.4

- core/tx_pool.go
- plugin/evm/config.go
- plugin/evm/config_test.go
- plugin/evm/vm.go
To avoid making manual patches for load testing: https://github.com/ava-labs/subnet-evm/tree/fix-load-test
Can be set via chain config
Unit tests.
> *: make tx pool configurable

- .github/workflows/lint-tests-release.yml
Ubuntu latest environment started to migrate further into 22.04, and the binaries compiled on it are incompatible with 20.04 at a dynamic lib level.
Compiling using 20.04 gets a binary that is ok for 20.04 and also for 22.04 due to the later supporting old binaries.
> use ubuntu 20.04 for making releases

- params/precompile_config.go
Prints out reward manager key
Adds reward manager key to String method of precompileKeys
Reactivated the precompile and seen key is properly shown.
> add reward manager key string

- consensus/dummy/consensus.go
- core/blockchain_reader.go
- core/state_transition.go
- core/tx_pool.go
- core/vm/evm.go
- eth/gasprice/gasprice.go
- params/config.go
- plugin/evm/block_verification.go
Reduces mandatory manual code addition for new precompiles ("ADD YOUR PRECOMPILE HERE")
Removes precompile specific functions from chain config and uses a generalized check function which takes precompile address.
Locally tested.
> generalize precompile specific upgrade checks

- cmd/simulator/go.mod
- cmd/simulator/go.sum
- compatibility.json
- go.mod
- go.sum
- params/precompile_config.go
- plugin/evm/version.go
- plugin/evm/vm_test.go
- scripts/versions.sh
This PR bumps the avalanchego dependency to v1.9.5-rc.0, which includes a change to the SNLookup to instead use the validator state in the `snow.Context`.
> Bump avalanchego to v1.9.5

- core/blockchain.go
- core/blockchain_reader.go
Adds a cache and reduces fetching data from state.
Adds a lru cache with limit 256. Uses it with the parent root in `GetCoinbaseAt` to reduce the number of reads of configured coinbase from statedb.
> add coinbase config cache

- accounts/abi/bind/precompile_template.go
- core/genesis.go
- core/state_processor.go
- miner/worker.go
- params/precompile_config.go
- precompile/allow_list.go
- precompile/contract.go
- precompile/contract_deployer_allow_list.go
- precompile/contract_native_minter.go
- precompile/fee_config_manager.go
- precompile/reward_manager.go
- precompile/stateful_precompile_config.go
- precompile/tx_allow_list.go
- precompile/utils.go
Removes panics in precompile functions and returns errors instead. Also refactors precompile create functions to make it more compact.
Changes `Configure` and `CheckConfigurePrecompiles` functions to return an error instead of panicking. 
Also refactors `create{Name}Precompile` functions to be more compact and clean-looking.
Locally generated reward manager precompile with tool and compared.
> rework on panics in precompiles

- commontype/fee_config.go
- contract-examples/README.md
- contract-examples/contracts/ExampleFeeManager.sol
- core/blockchain_reader.go
- core/stateful_precompile_test.go
- core/test_blockchain.go
- core/tx_pool.go
- eth/gasprice/gasprice.go
- eth/gasprice/gasprice_test.go
- miner/worker.go
- params/precompile_config.go
- plugin/evm/vm_test.go
- precompile/feemanager/config.go
- precompile/feemanager/config_test.go
- precompile/feemanager/contract.go
- precompile/params.go
Cleans up extra "config" word in the name
Renames struct
Existing UTs should cover this
Replaces #422
> rename fee manager config struct

- .github/ISSUE_TEMPLATE/release_checklist.md
This PR adds a release checklist template to help track all of the items that go into a Subnet-EVM release.
> Add release checklist template

- README.md
- cmd/simulator/go.mod
- cmd/simulator/go.sum
- compatibility.json
- go.mod
- go.sum
- plugin/evm/version.go
- scripts/versions.sh
This PR bumps the AvalancheGo dependency to v1.9.7 and starts the v0.4.9 release cycle.
> Bump avalanchego dep to v1.9.7 and start v0.4.9 release cycle

- plugin/main.go
This PR improves the output of the version command to display the version of AvalancheGo and RPCChainVMProtocol version that Subnet-EVM was built with.
This prints two additional constants in the version command imported from AvalancheGo.
```bash
aaronbuchwald@dhcp-vl2052-1520 subnet-evm % ../avalanchego/build/plugins/srEXiWaHuhNyGwPUi444Tu47ZEDwxTWrbQiuD7FmgSAQ6X7Dy --version
Subnet-EVM/v0.4.9@a584fcad593885b6c095f42adaff6b53d51aedb8 [AvalancheGo=v1.9.7, rpcchainvm=22]
```
> Improve version output

- core/state/snapshot/snapshot.go
- trie/database.go
Should release locks we take on returning from functions.
> release locks on return

- accounts/abi/bind/precompile_template.go
This PR fixes #464 
- adding missing import-statement "encoding/json"
- re-ordering of imports
it makes the precompile eventually compiling.
it adds a missing import-statement
- create a precompiled contract and compiles the whole repository with it
> Fixes #464: adding missing import "encoding/json" (used in Stringer-method)

- precompile/allow_list.go
> fix allow list comments

- commontype/fee_config.go
- commontype/fee_config_test.go
- params/precompile_config_test.go
- precompile/config_test.go
Prevents panic in fee config
adds nil checks 
added UT
> add nil checks

- plugin/evm/vm.go
Removes unnecessary function that would cause misunderstanding.
Removes unnecessary function
A successful compilation should cover this.
> remove current rules

- .github/CONTRIBUTING.md
Clarifies documentation guidelines
Explains our documentation standards for external contributors and clarifies them for ourself.
N/A
Self documenting :)
> add documentation guidelines

- contract-examples/hardhat.config.ts
Hardhat network config expects this to be an integer rather than a string.
Parses string env var to int.
On a local network.
This is a bugfix.
> parseInt from ENV var

- scripts/generate_precompile.sh
This PR should be merged in order to ensure that the CGO flags required by the blst library imported in AvalancheGo are set as required.
This PR addresses: https://github.com/ava-labs/subnet-evm/issues/483
This PR creates a new script `./scripts/create_precompile.sh` which sets the required constants and then runs the same command that `go run ...` command that was previously required to generate a precompile stub.
This was tested by completing step 0 of the PrecompileGen tutorial with one modification included in this PR: https://github.com/ava-labs/avalanche-docs/pull/1196
Change to PrecompileGen tutorial is documented here: https://github.com/ava-labs/avalanche-docs/pull/1196
> Add create precompile script to set CGO flag before running precompilegen script

- handlers/handler.go
- handlers/stats/mock_stats.go
- handlers/stats/stats.go
- handlers/warp/signature_request.go
- handlers/warp/signature_request_test.go
- handlers/warp/stats/stats.go
- plugin/evm/warp/backend.go
This PR re-organizes the stats and handlers and reduces the duplicated stats code.
This PR uses the embedded stats and handlers rather than duplicating function calls to do many passthroughs to the underlying stats.
This PR is tested in CI
no documentation necessary for this change
> Signature handler refactor

- .github/workflows/lint-tests-release.yml
Seems ubuntu-18 support is end of life-d on github.
This PR bumps our linter to use ubuntu-20.04 
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
> try to fix lint job

- go.mod
- go.sum
- plugin/evm/gossiper.go
- plugin/evm/warp/backend.go
- scripts/generate_precompile.sh
- scripts/versions.sh
Fixes build conflicts with Avalanchego v1.9.8
Provides a type specialization on the LRU cache used by the gossiper and the warp backend
CI
> build with avago v1.9.8

- .github/CONTRIBUTING.md
- .github/pull_request_template.md
- .github/workflows/lint-tests-release.yml
- contract-examples/hardhat.config.ts
- go.mod
- go.sum
- plugin/evm/gossiper.go
- plugin/evm/service.go
- plugin/evm/vm.go
- plugin/evm/warp/backend.go
- plugin/evm/warp_client.go
- plugin/evm/warp_service.go
- scripts/generate_precompile.sh
- scripts/versions.sh
> nits for get-signature-endpoint

- params/precompile_config.go
- precompile/stateful_precompile_config.go
Removes unnecessary and confusing function
Moves Configure in precompile function body to `ConfigurePrecompile` in precompile_config.
UTs and e2e tests should cover this
> remove unnecessary function

- .github/workflows/lint-tests-release.yml
This PR changes GH Actions to only run on tags that follow semantic versions and ignores rcs.
Addresses https://github.com/ava-labs/subnet-evm/issues/407
This updates from matching all tags to matching semantic versions.
Needs to be merged to test that rcs no longer trigger GH Actions to run and mark as latest release
No documentation necessary for this change.
> Update github actions to ignore rcs

- core/vm/contracts.go
- precompile/modules/registerer.go
- precompile/modules/registerer_test.go
Precompile address check should be done during module registration. The previous check was in `core/vm` package `init()`. Precompile Registration also happens on `init` function on precompile packages. This means that if `core/vm` is imported before `precompile` package, it could actually skip checking if the registered address equals to the blackhole address. 
Moves black hole address check from contracts init to `RegisterPrecompile`.
Added unit test
> move blackhole check to module registerer

- go.mod
- go.sum
- scripts/versions.sh
This PR bumps the AvalancheGo dependency to v1.9.9
See above
CI
No doc changes necessary
> Bump AvalancheGo dep to v1.9.9

- cmd/precompilegen/template-readme.md
> fix e2e comment in readme

- accounts/abi/bind/precompilebind/precompile_config_template.go
- accounts/abi/bind/precompilebind/precompile_contract_template.go
- accounts/abi/bind/precompilebind/precompile_module_template.go
Removes duplicate structs from config.go
Regenerated precompile for shared memory abi
> fix config template for precompilegen

- README.md
This PR should be merged to update the compatibility in the README for Subnet-EVM v0.4.10.
Updates README file
Just a README update
no additional docs needed for this PR
> Update compatibility in README for v0.4.10

- .github/workflows/lint-tests-release.yml
- Dockerfile
- README.md
- accounts/abi/bind/bind_test.go
- cmd/simulator/go.mod
- go.mod
- scripts/build.sh
Bumps the minimum golang version to v1.20.1.
As above.
CI
Updated README
> Bump minimum golang version to v1.20.1

- .github/workflows/lint-tests-release.yml
- Dockerfile
- README.md
- accounts/abi/bind/bind_test.go
- cmd/simulator/go.mod
- go.mod
- scripts/build.sh
go1.20.1 is not stable yet (https://github.com/golang/go/issues/58798). In the meantime, we'll stay on go1.19.6.
related: #548
> Set minimum golang version to go1.19.6

- internal/ethapi/api.go
- params/config.go
- params/config_test.go
It fixes the missing `upgrades` field in the GetChainConfig API
The embedded ChainConfig struct overrides MarshalJSON and prevents GetChainConfigResponse to call marshaller for UpgradeConfig. Added a Custom Marshaller to the GetChainConfigResponse type and rewritten the json accordingly.
Locally tested
This a fix, so current documentations are still correct.
> add custom marshaller for GetChainConfigResponse api

- accounts/abi/bind/precompilebind/precompile_module_template.go
- core/predicate_check.go
- core/predicate_check_test.go
- core/state/statedb.go
- miner/worker.go
- params/precompile_upgrade.go
- plugin/evm/block.go
- plugin/evm/config.go
- plugin/evm/vm.go
- precompile/precompileconfig/config.go
- utils/bytes.go
- utils/bytes_test.go
- warp/backend.go
- warp/backend_test.go
- warp/handlers/signature_request.go
- warp/handlers/signature_request_test.go
- warp/warp_service.go
This PR adds small changes in preparation for the warp precompile to reduce the warp PR's size.
- Updates hash slice encoding/decoding and add a unit test
- Changes the behavior of precompile predicates so that it does not require the proposervm header if a proposer predicate is enabled (proposervm will not always pass in a context before activation, so it is up to the precompile predicate to handle nil)
- Add Warp Message Writer interface into the `AcceptContext`
- Remove `ctx` from the warp backend interface
CI
No documentation changes required for this change.
> Warp preparation

- plugin/evm/gossiper.go
Fewer leaked goroutines in stopped chains (eg in some unit tests).
This releases tickers when the awaitEthTxGossip function returns.
UTs
No change.
> release tickers on shutdown

- precompile/contract/utils.go
Simplifies the function signature regex (removes unneeded [] and () and combines +? to *)
> simplify functionSignatureRegex

- eth/api.go
Follows upstream https://github.com/ethereum/go-ethereum/pull/26912
Uses 0644 as file permission for newly created files in export chain
CI
No changes needed.
> Matches go-ethereum/pull/26912/files

- accounts/abi/bind/precompilebind/precompile_contract_template.go
This PR fixes a possible unused import in the generated code from the contract template if the ABI package is not used.
Adds an `_ = abi.JSON` so that the generated file is still valid.
CI
No documentation changes necessary.
> Add ignore unnecessary import to precompile contract template

- peer/peer_tracker_test.go
Adds a UT for peer tracker.
Tests some assumptions.
CI
No changes.
> Adds a test for PeerTracker

- accounts/abi/bind/base.go
- eth/api_backend.go
- eth/gasprice/feehistory.go
- eth/gasprice/feehistory_test.go
- eth/gasprice/gasprice.go
- internal/ethapi/api.go
- internal/ethapi/backend.go
This PR syncs the changes from the following PRs made to geth:
- https://github.com/ethereum/go-ethereum/pull/26920
- https://github.com/ethereum/go-ethereum/pull/26922
CI
No documentation changes are necessary for this PR
> Sync geth nits

- plugin/evm/block.go
- plugin/evm/vm_test.go
This PR ports two changes from the warp PR that are not specific to that PR
- Add BLS public key and Warp signer to VM snow context setup
- Fix handling of receipts in precompile acceptance
CI
Added a comment to the receipt handling to make it more explicit
> Warp preparation updates

- scripts/install_avalanchego_release.sh
- scripts/versions.sh
Resolves #500
use the `AVALANCHE_VERSION` environment variable to specify a commit or branch name (or tag without a prebuilt binary).
tested here for a `commit`:
https://github.com/ava-labs/subnet-evm/actions/runs/4512439095/jobs/7945887581
and here for a `branch`:
https://github.com/ava-labs/subnet-evm/actions/runs/4512412729/jobs/7945824005
documentation for the whole process needs to be added
> Add ability to specify commit of avalanchego in ci

- core/blockchain.go
This PR renames a local variable to `validationTrieProcTime` for clarity
> Rename local var validationTrieProcTime

- .github/workflows/release.yml
This PR will match all goreleaser tags.
This will allow triggering goreleaser on a tag with `-fuji`. We should follow this up with a fix that runs goreleaser on any tag that does not include "rc", so that we can push non-standard tags.
> goreleaser match all tags

- plugin/evm/block.go
- plugin/evm/config.go
This PR addresses a few small nits from the warp prep changes.
- moves a debug log to a better location
- disables Warp API by default
CI
no documentation changes necessary.
> Warp prep nits

- .github/workflows/release.yml
This PR reverts the change to matching tags in https://github.com/ava-labs/subnet-evm/pull/607 to create the Cortina activation release and adds a manual workflow dispatch to trigger goreleaser when using non-standard tags.
> Add workflow dispatch for goreleaser and revert matching tags change

- accounts/abi/bind/backends/simulated.go
- core/blockchain.go
- internal/ethapi/api.go
- internal/ethapi/transaction_args.go
- plugin/evm/message/cross_chain_handler.go
- plugin/evm/syncervm_client.go
- plugin/evm/vm.go
- rpc/handler.go
- sync/handlers/block_request.go
- sync/handlers/code_request.go
- warp/handlers/signature_request.go
This PR updates the log levels in Subnet-EVM to ensure that they follow best practices.
Updates log levels
n/a
Debug - information useful for debugging that should not be surfaced in normal operation
Info - basic information about the program that a normal user would want to be aware of
Warn - not necessarily harmful, but unexpected
Error - should never happen and should cause a page to whoever is running the node and the maintainers of the repo to debug
Fatal - fatal error that should never happen has occurred
Note: the descriptions of Error and Fatal assume that the operator is using the application correctly. User error may lead to an error or fatal log that does not indicate a bug in the code.
There's a lot written up about log levels, but no canonical place for standards. Here is a …
> Update log levels

- README.md
- compatibility.json
- go.mod
- go.sum
- plugin/evm/version.go
- scripts/versions.sh
- tests/load/load_test.go
- tests/precompile/precompile_test.go
- tests/precompile/solidity/suites.go
This PR bumps avalanchego dependency to v1.10.0-fuji-rc.2 for the Fuji Cortina Release.
This also updates the Subnet-EVM version to v0.5.0-fuji-rc.0
> Bump avalanchego to v1.10.0

- plugin/evm/config.go
- plugin/evm/syncervm_client.go
- plugin/evm/vm.go
- sync/client/client_test.go
- sync/client/leaf_syncer.go
- sync/statesync/state_syncer.go
- sync/statesync/sync_test.go
Makes the number of state sync leafs requested configurable. Allows clients to try a smaller number if servers are overloaded.
Adds a configuration option
UT
TBD.
> Make state sync request size configurable

- peer/network.go
- peer/network_test.go
- plugin/evm/syncervm_test.go
Unblock state sync threads if shutdown is called
Invokes OnFailure for any pending messages
UT + manual testing on DFK sync (subnet-evm)
No changes needed.
> Fail outstanding app requests on shutdown

- contract-examples/test/contract_deployer_allow_list.ts
- contract-examples/test/contract_native_minter.ts
- contract-examples/test/reward_manager.ts
- contract-examples/test/tx_allow_list.ts
Will make changes in #601 easier to read/reveiw
Just deleting tests that are redundant or failing
N/A
N/A
> Delete redundant tests

- contract-examples/package.json
- contract-examples/test/README.md
- contract-examples/test/utils.ts
- contract-examples/yarn.lock
This code (and docs) are the ground-work for the soon to arrive full migration to `DSTest` in #601.
It looks like there's going to be some more back and forth on that PR, so I wanted to get this in earlier so that it can be used with the new precompiles that are currently being actively developed. 
pure magic
#601 
https://github.com/ava-labs/subnet-evm/pull/628/files
> Add DS-Test framework

- contract-examples/test/README.md
- contract-examples/test/utils.ts
Small improvement to the `contract-examples/test/utils.ts` file as well as the accompanying README.
This addresses the majority of comments from [here](https://github.com/ava-labs/subnet-evm/pull/628#pullrequestreview-1406066466)
> Improve clarity of test-utils for e2e precompile tests

- contract-examples/test/README.md
- contract-examples/test/utils.ts
In the DS-Test style tests, there is some ambiguity with what should/shouldn't constitue a test. This clears up that ambiguity by using `step_` as a clear differentiator of a prefixed method that should only be used in a testing context (as opposed to a helper). The issue with `test_` is that one might think they can fully understand a test from the `Solidity` method definition, without looking at how the method is being called from `TypeScript`. 
Same as before, just a different name
> Rename test_ to step_ for clarity

- .github/CODEOWNERS
CODEOWNERS matching on specific dirs overrides the global pattern match.
github
N/A
N/A
> Codeowners fix (specific dir overrides global)

- plugin/evm/gossiper.go
Simplify, eliminate unnecessary Hash op.
Just use the key in map iteration.
N/A
N/A
> plugin/evm: remove unncessary tx.Hash op in map iter

- contract-examples/scripts/deployExampleRewardManager.ts
Fixed incorrect contract call in deployExampleRewardManager.ts hardhat script; getContractFactory now correctly calls "ExampleRewardManager"
> deployExampleRewardManager.ts hardhat script fixed

- plugin/evm/config.go
This PR increases the trie dirty default cache size from 256MB to 512MB.
Increases the default value
CI
na
> Increase trie dirty default cache size to 512MB

- .github/workflows/ci.yml
It saves anr temporaries as CI artifact ready to download. Keep a record of full anr execution to better study/address problems/bug observed on CI, either during PR development or as a result of dependency changes. As CI is a particular env with limited resources, some times certain bugs are most easily observed here.
> save e2e anr artifacts

- contract-examples/package.json
- tests/load/load_test.go
- tests/precompile/precompile_test.go
- tests/precompile/solidity/suites.go
- tests/utils/command.go
It exports necessary test suite functions (before/after) to be used in other repos
Moves common after/before suites to utils package and exports them.
E2E tests 
It will be documented through external precompile registration tutorial.
> export gingkgo suites

- core/genesis_test.go
Removes unused line, matches coreth
N/A
UT
N/A
> remove unused line in test

- params/precompile_upgrade.go
- params/state_upgrade.go
State Upgrade functions should stay in its own file
Moves related functions to `state_upgrade.go`
Existing UT should cover this
No need
> move state upgrade related functions to own file

- warp/validators/state.go
This PR adds a wrapped validator state type to pass in to warp message verification. This reduces the number of signatures required to verify a message from the primary network using the assumptions:
1. A subnet already relies on its own validator set
2. A subnet's validator set is also validating the primary network
Wraps `validators.State` with a special case that will return the local snow context's validator set if the primary network validator set is requested.
na
comment in the code explaining the rationale
> Add wrapped validator state for primary to subnet warp messages

- .github/workflows/ci.yml
This PR uploads the anr data dir after the e2e tests run.
Uses upload-artifact GH action to upload relevant data for debugging e2e tests
CI
na
> upload network runner artifact after e2e test run

- params/avalanche_params.go
- params/protocol_params.go
- plugin/evm/vm.go
- warp/aggregator/aggregation_job.go
- warp/aggregator/aggregation_job_test.go
- warp/aggregator/aggregator.go
- warp/aggregator/network_signature_backend.go
- warp/aggregator/signature_job.go
- warp/aggregator/signature_job_test.go
- warp/backend.go
- warp/backend_test.go
- warp/handlers/signature_request.go
- warp/handlers/signature_request_test.go
- warp/handlers/stats/stats.go
- warp/warp_client.go
- warp/warp_client_fetcher.go
- warp/warp_service.go
This PR adds helpers to aggregate warp signatures using the network client and exposes an API endpoint, so that a client does not need to create its own network connection to request signature aggregation.
This creates a backend interface for fetching signatures that can use either an API or the network client to fetch warp signatures, a signature job to attempt requesting a signature, and an aggregator, which creates goroutines to fetch each signature and cancels ongoing jobs once a sufficient amount of stake's signatures have been acquired.
unit tests
na
> Add signature aggregation helpers

- .github/workflows/ci.yml
- contracts/package.json
- scripts/run_ginkgo.sh
- tests/precompile/precompile_test.go
- tests/precompile/solidity/suites.go
- tests/utils/command.go
- tests/utils/subnet.go
This PR runs all the Ginkgo tests in parallel, making the whole testing time twice as fast.
Ginkgo support running tests in parallel. This PR introduces a synchronized way to start an Avalanche Go node once, and setup one subnet for each tests to be run, and share those subnets IDs with the other processes.
We should have a green pipeline.
> Ginkgo tests parallel

- precompile/contract/interfaces.go
The current comment suggest that the BlockContext supplied to the precompile during execution is the block context during the activation of the precompile upgrade. This is not the case. 
Change comment to account both for execution and upgrade.
No test necessary, since only a comment.
> Fix BlockContext comment

- plugin/evm/block_builder.go
- plugin/evm/gossiper.go
- Copies changes from coreeth -> https://github.com/ava-labs/coreth/commit/61baf6dc01755513c195bd54c218b942d2d113d7
- Should speed up gossiping within subnet-evm
- Should improve TPS times 
PR description copied from @aaronbuchwald 
https://github.com/ava-labs/coreth-internal/pull/1253
This PR removes/refactors two delays in the path of mempool gossip.
Sleep 100 ms before gossiping newly received transactions to the network
This was added prior to Snowman++ to avoid the situation that a new node received transactions and then gossiped them immediately resulting in multiple nodes building a block in the expected case, which lead to unnecessary contention in consensus.
Since we've added Snowman++, this is no longer necessary except in the case that either 1) we are the next block proposer …
> Clean up gossip

- core/vm/evm.go
- go.mod
- precompile/contract/interfaces.go
- precompile/contract/mock_interfaces.go
This PR removes `CallFromPrecompile` from the accessible state of a precompile. Precompile development has led to many bugs in the past in projects that extended the EVM.
This PR removes this functionality for now since it is not currently used. This is intended to support a "less is more" approach for encouraging safe development while using Precompile-EVM until there is clear demand and guidelines for how to implement stateful precompiles safely.
If there is significant demand to add it back, we can re-support it and add better documentation as well.
Removes currently unused functionality.
CI
n/a
> Remove call from precompile

- core/genesis.go
- plugin/evm/vm.go
Moves Genesis verification to VM initialization.
> move genesis verify to vm

- accounts/abi/bind/bind.go
- accounts/abi/bind/precompilebind/precompile_contract_template.go
Fixes int types for uint and int8,16,32,64. also adds byte types.
changes the `converToNil` function and adds new cases.
Locally generated precompile files
No need as this is part of a generator tool
> Fix nil types tmpl

- accounts/abi/error_handling.go
- accounts/abi/unpack.go
- accounts/abi/unpack_test.go
This reverts commit 900eb39da6ae7690c05e64a43589568303cbd403 and migrates the changes from https://github.com/ethereum/go-ethereum/pull/26568.
This was reverted to separate it from the rest of the coreth sync changes.
> Revert "revert unpack changes"

- params/config.go
Timestamp upgrades were not shown correctly. 
Changes verb and use value from pointers
Locally tested to see output
No need.
> change sprintf verb and use values

- tests/utils/runner/network_manager.go
- tests/warp/warp_test.go
Fixes an issue which improperly assigns all e2e test endpoints to the first blockchain.
Fixes the issue.
Also brings back a 2nd "triggerTx" on blockchain B in the warp test since otherwise the test gets stuck on waiting for a new block.
CI
N/A
> e2e test: connect to appropriate chain

- plugin/evm/block_builder.go
Adds debug log for when we skip a build block notification 
Adds debug log
Did not
N/A
> add debug log for dropped pending txs notifications

- plugin/evm/vm.go
Closes #779 
Force registers js tracer package to the vm
locally tested to see if crashes.
This is a bugfix.
> force register js tracer

- .github/workflows/ci.yml
- contracts/README.md
- contracts/package-lock.json
- contracts/package.json
* Updates npm package dependencies 
* uses clean install for npm 
e2e tests should cover this
no need
> update npm package

- accounts/abi/bind/precompilebind/precompile_config_template.go
- accounts/abi/bind/precompilebind/precompile_module_template.go
- params/precompile_upgrade.go
- precompile/allowlist/allowlist_test.go
- precompile/allowlist/config.go
- precompile/contract/interfaces.go
- precompile/contract/mock_interfaces.go
- precompile/contracts/deployerallowlist/config.go
- precompile/contracts/deployerallowlist/module.go
- precompile/contracts/feemanager/config.go
- precompile/contracts/feemanager/module.go
- precompile/contracts/nativeminter/config.go
- precompile/contracts/nativeminter/module.go
- precompile/contracts/rewardmanager/config.go
- precompile/contracts/rewardmanager/module.go
- precompile/contracts/txallowlist/module.go
- precompile/precompileconfig/config.go
- precompile/precompileconfig/mock_config.go
- precompile/testutils/test_config.go
- precompile/testutils/test_precompile.go
- x/warp/config.go
- x/warp/config_test.go
- x/warp/module.go
Takes chainconfig to verify as a parameter so that custom verification depending on chain config (like network upgrades) can be done.
> Expand verify

- precompile/contract/contract.go
- precompile/contract/utils.go
Adds activation function to precompile functions. Activation Functions denotes that if the underlying precompile function has been activated or not.
If not activated it returns "signature not found" as if this function never exists.
Changes new precompile function constructor 
WIll be tested with manager role
> add activation func to precompile functions

- warp/aggregator/aggregation_job.go
- logs the subnetID and height at the start of a signature aggregation job
- adds an improved error when there are no validators to aggregate a signature from
This is in response to an unhelpful error reported in https://github.com/ava-labs/subnet-evm/issues/806
CI
na
> warp/aggregator: improve logs/error for signature aggregator

- core/types/gen_receipt_json.go
- core/types/receipt.go
Better compatibility with coreth & upstream. See:
https://github.com/ava-labs/coreth/blob/master/core/types/receipt.go#L75
https://github.com/ethereum/go-ethereum/blob/v1.12.0/core/types/receipt.go#L65
Forces inclusion of effectiveGasPrice
Uncovered in updating t8n PR.
N/A
> Serialize EffectiveGasPrice like upstream

- core/predicate_check.go
- core/predicate_check_test.go
- core/state_transition.go
- miner/miner.go
- miner/worker.go
- params/config.go
- plugin/evm/block.go
- plugin/evm/vm.go
- precompile/contract/interfaces.go
- precompile/precompileconfig/config.go
- precompile/testutils/test_predicate.go
- x/warp/config.go
- x/warp/predicate_test.go
This PR aligns precompile predicates on a single type instead of separating out into with/without the ProposerContext.
as above
CI
na
> Align on a single predicate type

- core/state/snapshot/snapshot.go
This PR migrates https://github.com/ethereum/go-ethereum/pull/27977.
This increases the cap on the size of a batch when flattening a snapshot diff layer to disk. This is a non-atomic operation to ensure that flattening does not create such a large batch that it causes an OOM.
However, breaking this up may result in invalidating the snapshot since you may apply only part of the change, which results in needing to re-generate the snapshot.
Increasing the capped size to 64MB provides a reasonable cap to avoid an OOM and drastically increases the size of a diff that is needed to potentially corrupt a snapshot.
> core/state/snapshot: increase batch size during diffToDisk

- precompile/precompileconfig/config.go
- precompile/precompileconfig/mocks.go
This PR breaks out adding `IsDUpgrade` to the precompileconfig ChainConfig interface from https://github.com/ava-labs/subnet-evm/pull/801/files, which is needed to address: https://github.com/ava-labs/subnet-evm/pull/823#discussion_r1309368416
> precompile/precompileconfig: Add IsDUpgrade to precompileconfig ChainConfig interface

- accounts/abi/bind/bind_test.go
This PR marks `TestGolangBindings` as flaky. Example run: https://github.com/ava-labs/subnet-evm/actions/runs/6025850127/job/16347487265?pr=823
> accounts/abi/bind: mark TestGolangBindings as flaky

- warp/validators/state_test.go
This PR adds a unit test for retrieving the validator set via the warp wrapped validator state.
> warp/validators: add unit test for warp wrapped validator state

- warp/payload/README.md
This PR adds a README to document the warp payload types.
> warp/payload: add README for payload serialization

- .github/workflows/auto-generated-code-checker.yml
- .github/workflows/check-clean-branch.sh
- precompile/contract/mocks.go
- scripts/mock.gen.sh
- scripts/mocks.mockgen.txt
We have added mock.gen.sh in the PR https://github.com/ava-labs/subnet-evm/pull/801. This one adds a CI job to ensure we're applying it correctly (as we do in avalanchego)
https://github.com/ava-labs/subnet-evm/pull/801#discussion_r1314280082
CI
> add mock ci

- params/network_upgrades.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
- plugin/evm/vm_upgrade_bytes_test.go
- tests/precompile/genesis/contract_deployer_allow_list.json
- tests/precompile/genesis/contract_native_minter.json
- tests/precompile/genesis/fee_manager.json
- tests/precompile/genesis/reward_manager.json
- tests/precompile/genesis/tx_allow_list.json
- tests/precompile/genesis/warp.json
From comment:https://github.com/ava-labs/subnet-evm/pull/801#discussion_r1314279711
Adds a way to override enforced mandatory upgrades. Mandatory upgrades are still enforced for mainnet and fuji, but rest of the networks (unit tests and local) can be overridden. 
We conditionally enforce.
Expanded the current unit tests
No need.
> override network upgrades

- x/warp/predicate_test.go
This PR adds a unit test for verifying a warp message from the Primary Network correctly uses the validator set of the receiving subnet.
> x/warp: add predicate test for warp message from Primary Network

- plugin/evm/network_handler.go
- plugin/evm/vm.go
- warp/backend.go
- warp/backend_test.go
- warp/handlers/signature_request.go
- warp/handlers/signature_request_test.go
- warp/warp_service.go
Removes stuttered name.
N/A
N/A
N/A
> rename `WarpBackend` to `Backend`

- go.mod
- go.sum
- plugin/evm/vm.go
- scripts/versions.sh
Syncs corresponding PR from Coreth: https://github.com/ava-labs/coreth/pull/334
> Drop outbound gossip for non vdrs

- plugin/evm/vm.go
- warp/backend.go
- warp/backend_test.go
- warp/handlers/signature_request_test.go
Reduces interface. We only need one field of the snow.Context, so let's just pass that in.
Self-explanatory.
Existing UT.
New interface.
> pass warpSigner instead of snow context into backend

- peer/client.go
- peer/network.go
- peer/network_test.go
- sync/client/client.go
- sync/client/mock_network.go
This is an additional supplement to Dan's PR on the `add-contexts` branch. 
All Send functions in Networking now take in a context. 
If contexed cancelled prior to being called, we should return a ctx cancelled err. We also don't generate a new context on sends and instead pass the existing one through. 
UT
> Add Contexts Continued 

- contracts/contracts/ExampleWarp.sol
- contracts/contracts/interfaces/IWarpMessenger.sol
Interfaces in solidity following convention of naming starting with "I".
Updated interface to `IWarpMessenger` instead of `WarpMessenger`, and updated places that use it in subnet-evm
n/a
n/a
> Update IWarpMessenger interface name

- warp/aggregator/signature_getter.go
Using `time.After` can leave a hanging goroutine.
Refactor loop.
Existing UT
Comments
> use timer instead of time.After

- core/state/statedb.go
Doc is outdated, we now support multiple access tuples with the same precompile address. 
n/a
n/a
n/a
> Update preparePredicateStorageSlots doc

- core/predicate_check.go
- core/state/statedb.go
- utils/predicate/predicate_slots.go
In `predicate_check` and `state_db` we were duplicating code for preparing the predicate storage slots from a transaction's access list. This PR consolidates them to a `util` function to make sure they're in sync and reduces duplication.
- Creates separate file in utils `predicate_slots.go`
- Create utils `PreparePredicateStorageSlots` function
- Use util function for previous places.
n/a
comments in code
> Consolidate predicate prepare storage slots function

- precompile/results/predicate_results.go
- precompile/results/predicate_results_test.go
More consistent behavior for SetTxPredicateResults. This also matches the existing comment which suggests present results will be overrided.
Removes an previous entries from the map if an empty entry is provided for the same Tx hash.
CI
Updated comments
> SetTxPredicateResults: Consistent overwriting

- .github/CONTRIBUTING.md
- README.md
- core/txpool/list.go
- metrics/README.md
Some links have been moved, updated to the latest version.
Clicking on the current links used to go to the old links and then redirect to the new ones, now it will go directly to the new ones. 
I clicked on the links and realized there was a redirection.
There seemed to be no need to document it.
> Fixed some golang links.

- core/predicate_check.go
- core/predicate_check_test.go
- x/warp/config.go
- x/warp/predicate_test.go
Verification of a predicate requires a the predicate context. If the predicate context is missing, we should invalidate the whole block rather than marking the result of the predicate as failed.
Moves the check out of the warp package and into the core package.
CI
With a comment
> Invalidate block when missing predicate context

- warp/backend.go
- warp/backend_test.go
We should be clearing all of the state from the `backend`.
Clears cache on `Clear`.
New UT
N/A
> clear messageCache on backend.Clear

- .github/ISSUE_TEMPLATE/release_checklist.md
This PR adds deploying to WAGMI to the Subnet-EVM release process checklist.
> Update release checklist to include deploying to WAGMI

- .github/workflows/ci.yml
- core/state/snapshot/conversion.go
Newer version of golangci-lint includes better linters incl. the wspace linter
Bumps the version
First commit fails lint on this PR (expected)
N/A
> bump golangci-lint

- warp/aggregator/aggregator_test.go
This unit test simulates the scenario where the context is canceled midway through signature fetching. 
All signature fetching go routines prior to cancellation should be able to get a signature. 
All signature fetching go routines after cancellation should return with context cancelled error and no signature. 
The result should have an aggregate signature from only one validator.
Only adds a UT. No actual change to any prod code. 
UT is commented.
> Add Unit Test for Test Aggregate Signatures

- plugin/evm/vm_warp_test.go
- tests/warp/warp_test.go
- x/warp/config.go
- x/warp/contract.go
- x/warp/contract_test.go
Replaces: #924 
Fixes the event packing for data for `SendWarpMessage`.
Fixes: #894
Uses `abi` package `PackEvent`/`UnpackIntoInterface` functions to properly pack/unpack messages for event data.
Fixes failing e2e tests. adds new UT tests.
> fix warp event packing

- tests/warp/warp_test.go
Setups should be in beforesuit:
https://github.com/ava-labs/subnet-evm/pull/935#discussion_r1347564463
> move setup to beforesuite

- x/warp/config.go
- x/warp/contract_test.go
- x/warp/contract_warp_handler.go
- x/warp/predicate_test.go
Warp messages are encoded in the transaction's access list as a predicate, and the result of verifying the predicate with calling VerifyPredicate (success, fail) is stored the header as an encoded bitset. If we expect most of the transactions to represent successes (as opposed to txs that pay gas but reference invalid warp messages in the predicate), we can use 0 to encode success and 1 to encode failure.
This change has the advantage of using the empty byte slice to represent a valid transaction that only specifies valid warp messages.
The current implementation does the opposite: 1 for success and 0 for failure, which adds one or more bytes in the header for valid txs that only specify valid warp messages.
Changes the logic to add 1 to the bitset on error instead of success
CI + …
> warp: use bitset in predicate results to encode indexes of failures instead of success

- accounts/abi/bind/bind_test.go
- accounts/abi/bind/precompilebind/precompile_bind_test.go
I've run this few hundreds (even thousands) of times and got no flakiness. I wonder if this was because in some very rare cases we were overwriting the temp dir with the precompilebind tests. I changed the path for precompile bind tests and removed flaky flag.
Closes #828
> remove flaky flag from golangbindings test

- plugin/evm/block.go
This PR removes a call to `.Bytes()` so that it directly casts a 32 byte array to a different alias.
> plugin/evm: update type cast to skip call to Bytes()

- x/warp/config.go
- x/warp/predicate_test.go
This PR updates `PredicateGas` of the warp precompile to parse the payload included in a warp message and return an error if it does not match a valid payload format defined by AvalancheGo.
> x/warp: update PredicateGas to require warp message contains a valid payload

- scripts/build_image.sh
- scripts/constants.sh
- scripts/mock.gen.sh
Ports changes from https://github.com/ava-labs/avalanchego/pull/2184 to fix flaky mockgen.
Closes: #972 
Uses `-O2` flag for CGO flags and imports it in mockgen script.
This should fix flaky tests.
> use cgo in mockgen

- plugin/evm/vm.go
Closes: #977 
Fixes API admin registration bug.
Removes extra service registiration in helper function.
> remove extra service registration

- core/chain_makers.go
- eth/tracers/api.go
- eth/tracers/api_test.go
Currently we don't apply upgrades in tracing. This PR adds regression test + fix.
Closes: #976 
Call ApplyUpgrades before applying transactions in the tracer.
added regression test
> Fix tracer precompile upgrade

- plugin/evm/block.go
- plugin/evm/block_test.go
- precompile/precompileconfig/config.go
- precompile/precompileconfig/mocks.go
- x/warp/config.go
Adds more information to the log emitted when a block sending warp messages are accepted.
Passes through blockNumber, blockHash.
CI
N/A
> warp: add details to accepted message log

- README.md
- compatibility.json
- go.mod
- go.sum
- plugin/evm/syncervm_test.go
- plugin/evm/version.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
- scripts/versions.sh
Bump avalanchego dependency to v1.10.15
updates go.mod & go.sum
CI
N/A
> bump avalanchego to v1.10.15

- warp/handlers/signature_request_test.go
This PR updates an assertion on the amount of time spent serving a request from using a duration to int64 value to match the value reported by the metric.
This fixes an error when running on Windows migrating this code to Coreth: https://github.com/ava-labs/coreth/actions/runs/6852336438/job/18630638235?pr=387
> warp/handlers: update duration greater than assertion to pass on windows

- tests/warp/warp_test.go
- warp/backend.go
- warp/client.go
- warp/service.go
This PR adds a `subnetIDStr` argument to the Warp APIs, so that the caller can specify what subnetID's validator set the API should attempt to fetch validator signatures from.
This is used in the case of the C-Chain, so that signatures from subnetA can be fetched when aggregating signatures for a message that needs to be sent to subnetA.
> Add subnetID arg to warp APIs

- cmd/simulator/key/key.go
- cmd/simulator/load/funder.go
- cmd/simulator/load/loader.go
- cmd/simulator/load/worker.go
- cmd/simulator/metrics/metrics.go
- cmd/simulator/txs/agent.go
- cmd/simulator/txs/tx_generator.go
This PR refactors the load simulator to better support async tx sequence generation for warp load testing.
It also better separates some of the load simulator code (still significant room for improvement).
Specific changes:
- add tx worker version that confirms transactions by receipt instead of nonce
- add confirm reached tip helper function to confirm all workers have observed the latest tip (as of calling the function)
> cmd/simulator: refactor simulator to support warp load test

- core/state_processor.go
Removes unnecessary assignment
Removes unnecessary assignment
Existing tests should cover this
> remove unnecessary assignment

- params/config.go
- plugin/evm/block_builder_test.go
- plugin/evm/vm_test.go
- precompile/testutils/test_precompile.go
- utils/snow.go
- warp/handlers/signature_request_test.go
- warp/validators/state_test.go
- x/warp/contract_test.go
- x/warp/predicate_test.go
We're removing `snow.DefaultContextTest` in AvalancheGo (https://github.com/ava-labs/avalanchego/pull/2518)
add func and use it
CI
> Add `TestSnowContext` util

- .github/workflows/auto-generated-code-checker.yml
- .github/workflows/bench.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile
- README.md
- scripts/build.sh
Bumps minimum go version to 1.20.12 (same with avalanchego)
Replaces 1.20.11 > 1.20.12
bumps golangci version
UTs should cover this
Changed readme
> bump min go version

- plugin/evm/gossip.go
- plugin/evm/gossip_test.go
- plugin/evm/gossipper_test.go
There is a bug that prevents pending txs to be added to bloom filter after reset.
Change variables from pendingTxs to iterated txs 
Added UT
No need
> Fix bloom reset

- core/vm/contracts.go
- go.mod
- go.sum
The issue requiring use of the alternate library was resolved in go 1.20
This aligns with coreth & upstream
Removes use of big library in favor of standard library.
CI
N/A
> Remove big2 library

- warp/client.go
- warp/service.go
Exposes `GetMessage` in the Warp API. The use case is for clients (such as awm-relayer) to fetch a Warp message while only needing to know the ID, not the full message bytes.
Corresponding coreth PR: https://github.com/ava-labs/coreth/pull/465
Adds `GetMessage` to client.go and service.go
Manually tested via the client in a local deployment
N/A
> Expose GetMessage in Warp API

- eth/tracers/internal/tracetest/calltrace_test.go
- eth/tracers/native/call.go
- eth/tracers/native/prestate.go
Applies patch from https://github.com/ava-labs/coreth/pull/371 to subnet-evm as well
Takes upstream code https://github.com/ethereum/go-ethereum/pull/27691/files
CI
N/A
> eth/tracers/native: migrate fix for memory read in prestate tracer

- cmd/abigen/namefilter.go
- cmd/abigen/namefilter_test.go
- eth/tracers/internal/tracetest/flat_calltrace_test.go
- eth/tracers/internal/tracetest/util.go
- rpc/client_opt_test.go
Makes all the avalanche headers 10 lines long, so it's easy to handle them in a script
Adds comments
CI
N/A
> Add line of stars to comment header

- accounts/abi/bind/backends/simulated.go
- eth/api.go
- eth/api_backend.go
- eth/filters/filter.go
- eth/filters/filter_system_test.go
- eth/filters/filter_test.go
- rpc/types.go
Seems in geth the rpc numbers (when resolved to real blocks) semantically follow a pattern of
Finalized <= Safe <= Latest <= Pending
Since we don't have Pending, we can map Latest/Pending to the chain's head in unfinalized query mode
Without unfinalized query mode, we can use last accepted for all.
Updates semantics as above
Aligns code with upstream & adds FinalizedBlockNumber as an alias for AcceptedBlockNumber (esp in tests)
CI
not yet
> eth/filters, eth/api: update rpc numbers in unfinalized query mode

- core/txpool/txpool.go
- internal/ethapi/api_test.go
These were noted during applying the geth sync to coreth, so we can apply them here as well.
> fix test reliability

- ethclient/ethclient.go
When a project like ```avm-relayer``` imports ```ethclient/ethclient.go``` as a package it ensures that all precompiles defined in ```precompile/registry/registry.go``` are registered.
This fixes the ```unknown precompiled configuration: ``` error in the unmarshalling of ```params.ChainConfigWithUpgradesJSON```. Bugs and reproduction steps documented in https://github.com/ava-labs/awm-relayer/issues/226
> Force precompile modules registration by importing ethclient as a package

- .github/workflows/release.yml
We have changed this to include pre-releases (fuji) but this also includes release candidates (rc). We should only release for full versions and if there is something we want to release (as pre-release) we can trigger it manually.
> disable running for all tags

- core/state_processor.go
- core/state_processor_test.go
- core/vm/runtime/runtime.go
- go.mod
- internal/ethapi/transaction_args_test.go
- params/config.go
- params/config_extra.go
- params/config_test.go
- params/network_upgrades.go
- params/network_upgrades_test.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
- plugin/evm/vm_upgrade_bytes_test.go
- tests/init.go
1- This adds a new upgrade config `networkUpgradeOverrides` to override any avalanche network upgrade. With this upgrade config and `skip-upgrade-check` flag set to true, one can modify the timestamp of activated upgrade. This will come handy if a subnet has missed the upgrade (failed to update nodes) and as a result their chain has become unsyncable with newer versions. In this case `networkUpgradeOverrides` can be used to set a later time for upgrades. I.e:
`upgrade.json`:
```
{
"networkUpgradeOverrides": {
"durangoTimestamp": 1710415083
}
}
```
2- Default Network Upgrades are introduced. `nil` and `blank` values in network upgrades (eth forks + avalanche upgrades) will now default to values. Meaning that it won't be possible to deactivate an existing upgrade via `nil` values. 
3- This …
> Genesis chainconfig cleanup

- .github/workflows/notify-metrics-availability.sh
- .github/workflows/tests.yml
- scripts/run_prometheus.sh
- scripts/run_promtail.sh
- tests/README.md
- tests/load/load_test.go
- tests/utils/tmpnet.go
- tests/warp/warp_test.go
Adds collection of logs and metrics for warp and load testing to aid in debugging. 
- starts agent-mode prometheus and promtail before the test run
- tmpnet writes prometheus and promtail configuration when starting nodes
- ci jobs are configured with the environment necessary to label metrics  
- Checked that links emitted by the 2 jobs using tmpnet opened a grafana page that was correctly filtered and contained data for the test run
- Checked that a manual loki query was possible 
- Added brief overview to tests/README.md with a link to the relevant avalanchego docs. There is an outstanding [PR](https://github.com/ava-labs/avalanchego/pull/2854/files) that improves the relevant avalanchego docs.
> `ci`: Enable collection of logs and metrics

- peer/network.go
Fixes issue that caused unexpected `AppResponse` / `AppRequestFailed` messages to be reported.
The `rpcChainVM` does not guarantee that returning an error from these methods implies that the messages was not sent to the peer.
Calling `warp_getBlockAggregateSignature` and closing the TCP connection during the request causes the context to be cancelled here. After this fix was introduced the issue is no longer able to be replicated.
Comments
> Remove cancellation for Send.*AppRequest messages

- .github/workflows/bench.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- Dockerfile
- README.md
- go.mod
- scripts/build.sh
Bumps golang version to 1.21.9 in go.mod file and removes check in build script.
CI & locally tested
No need
> Bump go version

- core/state/snapshot/snapshot.go
- go.sum
Excerpts from https://github.com/ava-labs/subnet-evm/actions/runs/8725583610/job/23938886724?pr=1154
```
Previous write at 0x00c0075f5590 by goroutine 14701:
github.com/ava-labs/subnet-evm/core/state/snapshot.(*diskLayer).generate()
/home/runner/work/subnet-evm/subnet-evm/core/state/snapshot/generate.go:402 +0x238e
github.com/ava-labs/subnet-evm/core/state/snapshot.generateSnapshot.func1()
/home/runner/work/subnet-evm/subnet-evm/core/state/snapshot/generate.go:160 +0x44
Goroutine 14701 (running) created at:
github.com/ava-labs/subnet-evm/core/state/snapshot.generateSnapshot()
/home/runner/work/subnet-evm/subnet-evm/core/state/snapshot/generate.go:160 +0x71b
github.com/ava-labs/subnet-evm/core/state/snapshot.(*Tree).Rebuild()
/home/runner/work/subnet-evm/subnet-evm/core/state/snapshot/snaps …
```
> snapshot: fix race in abort/generate

- core/txpool/legacypool/legacypool.go
- core/txpool/legacypool/legacypool_test.go
Re-open PR, because my previous PR was broken due to not signed the commit.
Ensure that transactions added to the legacy pool are not treated as 'locals' if the global locals-management has been disabled.
Actually This PR from go-ethereum.
https://github.com/ethereum/go-ethereum/pull/28435
This change makes the pool enforce the --txpool.pricelimit setting.
-
-
> respect nolocals-setting

- accounts/abi/bind/bind.go
- consensus/dummy/dynamic_fees.go
- core/blockchain.go
Fix mismatched method names in comments
> Fix mismatched method names in comments

- .github/workflows/tests.yml
- .golangci.yml
- consensus/dummy/consensus.go
- core/blockchain_test.go
- core/state_processor_test.go
- core/test_blockchain.go
- eth/backend.go
- eth/chain_with_final_block.go
- metrics/opentsdb_test.go
- miner/worker.go
- plugin/evm/block_verification.go
- plugin/evm/gossip.go
- plugin/evm/gossip_test.go
- plugin/evm/syncervm_test.go
- plugin/evm/vm_test.go
- scripts/build_test.sh
- scripts/lint.sh
- sync/syncutils/test_trie.go
Syncs the PR https://github.com/ava-labs/coreth/pull/527
> Coreth sync nits

- metrics/sample_test.go
Skip the flaky test, we don't modify this code anyways.
> mark TestExpDecaySampleNanosecondRegression flaky

- log/format.go
- log/logger.go
Fixes level spacing problems like
`[05-07|12:25:21.446] DEBUG<hBRSYikeL9fzeioygWcgDKFtEnaGsLS5VFxRFNxUiDpan79rg Chain> plugin/evm/gossip.go:138 shutting down subscription
`
> fix space in log levels

- core/blockchain.go
- core/blockchain_test.go
- eth/backend.go
- eth/ethconfig/config.go
- plugin/evm/syncervm_test.go
- plugin/evm/vm.go
New `transaction-history` flag was not being passed correctly.
Removes old `TxLookupLimit` config (keeps the flag) and uses the new `TransactionHistory` config and correctly deprecates old one and uses the new one.
Locally
Already documented
> fix transaction history flag

- core/txpool/txpool.go
The txpool stores the last set gastip in addition to setting it in the subpools.
So it should be set on init.
The value is only read in tests.
> remember initial gasTip

- .github/workflows/bench.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- Dockerfile
- README.md
- compatibility.json
- core/state/snapshot/snapshot.go
- go.mod
- go.sum
- plugin/evm/syncervm_client.go
- plugin/evm/version.go
- plugin/evm/vm.go
- scripts/versions.sh
> Bump versions

- ethclient/ethclient.go
- ethclient/subnetevmclient/subnet_evm_client.go
- interfaces/interfaces.go
These fields were missing. Notably, accessList is needed for warp gas estimation.
Passes the missing fields along.
Against https://github.com/ava-labs/teleporter/tree/gas-estimate which issues gas estimation calls with warp.
N/A
> add missing fields to "toCallArg"

- sync/statesync/trie_sync_stats.go
- sync/statesync/trie_sync_stats_test.go
This calculation has the potential to overflow:
now.Sub(t.triesStartTime) * time.Duration(t.triesRemaining)
`time.Duration(t.triesRemaining/t.triesSynced)` is less likely to overflow as the ratio decreases as the time passed goes on.
CI
N/A
> Fix overflow in state sync eta

- go.mod
- tests/load/load_test.go
- tests/precompile/precompile_test.go
- tests/utils/command.go
- tests/utils/subnet.go
- tests/warp/warp_test.go
Previously gomega was replaced by testify so that only a single assertion library was used across all types of testing. The replacement was incomplete, though, since registration of a fail handler for gomega was still being performed and somehow the  `tests/utils` path was missed entirely. This changeset removes the use of gomega entirely.
CI
> [testing] Remove dep on gomega

- sync/statesync/state_syncer.go
Fixes https://github.com/ava-labs/subnet-evm/issues/1200
Closes the sync channel after the last storage trie has finished (or if there is no storage tries).
This avoids writing to a closed channel when a storage trie splits into segments:
https://github.com/ava-labs/subnet-evm/blob/master/sync/statesync/trie_segments.go#L311-L313
but in the existing behavior the storageTrieProducer could have previously closed the channel.
CI
N/A
> resolve race in closing sync segments channel

- contracts/package-lock.json
- contracts/package.json
- contracts/tsconfig.json
In the previous version we introduced a broken tsconfig which would skip `index.js` to be packed, and also dist package did not updated from 1.2.0. This fixes those issues by reverting tsconfig and bumping to 1.2.2 
Locally against precompile-evm
> update tsconfig & bump to 1.2.2

- plugin/evm/vm_test.go
These tests directly query the blockchain without the API layer and are not impacted by this setting
> unneeded SetAllowUnfinalizedQueries

- core/rawdb/accessors_snapshot.go
- core/rawdb/accessors_state_sync.go
- core/state/snapshot/snapshot_test.go
make function comments match function names
> chore: make function comments match function names

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- scripts/actionlint.sh
Adds linter for github action configuration in keeping with a [similar addition to avalanchego](https://github.com/ava-labs/avalanchego/pull/3160).
> [ci] Add actionlint job

- .github/workflows/tests.yml
Switches to use the actions enabling monitoring and artifact collection for tmpnet usage defined by avalanchego. This avoids having to maintain duplicated action configuration.
> [ci] Simplify configuration of monitoring for CI jobs

- scripts/build.sh
- scripts/constants.sh
VMIDs are not constant for repos but per-chain, thus plugin binaries can be created with any name. 
If no parameter is provided, defaults to avalanchego plugin folder path
Removes symlinking with constant VM ID.
Locally
No need
> use default path to build, remove symlinking

- go.mod
- go.sum
- plugin/evm/vm.go
- warp/backend.go
- warp/handlers/signature_request.go
- warp/handlers/signature_request_p2p.go
- warp/handlers/signature_request_p2p_test.go
https://github.com/ava-labs/subnet-evm/issues/1259 
Adds support for ACP-118 message types.
Assumes that 32 bytes messages should be interpreted as a block hash
This PR mostly adopts the existing code to the new handlers & protos as defined in ACP-118.
CI
N/A
> add p2p handler for acp-118 sig request

- go.sum
- plugin/evm/tx_gossip_test.go
- plugin/evm/vm.go
Use the constant that is reserved for this protocol.
Alternatively can keep `ethTxGossipProtocol = p2p.TxGossipHandlerID`, not very opinionated.
> cleanup: use p2p.TxGossipHandlerID

- Dockerfile
- scripts/versions.sh
- the next lines in the dockerfile are looking for the binary at build/subnet-evm so build it there
- the shorter commit matches a dockerhub tag so it's possible to use that to build a subnet-evm docker image, but not the full commit. for this reason I think we should prefer the shorter commit refs for avalanchego version.
> fix docker build

- eth/filters/filter_system.go
Current code seems to mix the handling of pending/accepted txs.
As is the `accepted` bool doesn't impact whether or not the tx is published to the pending feed.
Separate code paths
CI (maybe needs a ut)
N/A
> handle accepted/pending tx subs separately

- eth/tracers/api_test.go
- internal/ethapi/api_test.go
resolves the todo and reduces diff w/ upstream
> nit: resolve TODO in api_test.go

- params/config.go
- params/config_extra.go
- params/network_upgrades.go
- params/network_upgrades_test.go
- plugin/evm/vm_test.go
- utils/snow.go
Uses chainCtx.NetworkUpgrades to determine default values
takes an avalanchego upgrade config to set defaults.
UTs modified 
the avalanchego flag is not documented yet. this PR honors that flag so the main flag doc should be sufficient.
> use ctx network upgrades

- .github/workflows/publish_antithesis_images.yml
- .github/workflows/tests.yml
- .github/workflows/trigger-antithesis.yml
- .gitignore
- Dockerfile
- go.mod
- go.sum
- scripts/build_antithesis_images.sh
- scripts/build_antithesis_workload.sh
- scripts/build_docker_image.sh
- scripts/install_avalanchego_release.sh
- scripts/shellcheck.sh
- scripts/tests.build_antithesis_images.sh
- scripts/versions.sh
- tests/antithesis/Dockerfile.config
- tests/antithesis/Dockerfile.node
- tests/antithesis/Dockerfile.workload
- tests/antithesis/README.md
- tests/antithesis/gencomposeconfig/main.go
- tests/antithesis/main.go
This PR adds the scaffolding required to build images for an antithesis test setup for subnet-evm.
Adds scripts, dockerfiles and code that comprise the antithesis test setup and its tooling.
New CI job checking workload sanity and construction of the images.
**NOTE:** Due to the limitations inherent to github actions, validation of image publication and the triggering of antithesis workloads can only be performed once this PR is merged.
> [antithesis] Add initial test setup

- scripts/build_test.sh
I don't want to address whether the race detector should run on every CI right now, but I keep finding myself removing the `-race` option and sometimes it gets committed by mistake, then have to undo it, or keep stashing this change.
So this adds support for running tests like `NO_RACE=1 ./scripts/build_test.sh`
> add NO_RACE so uts can run faster locally

- .github/workflows/trigger-antithesis.yml
Ensures regular execution of subnet-evm test setup.
- adds a cron schedule to the trigger workflow
- manually invoked the test setup successfully
- inline
> [antithesis] Add schedule for test setup

- .github/workflows/tests.yml
- go.mod
- go.sum
- scripts/run_prometheus.sh
- scripts/run_promtail.sh
- scripts/versions.sh
The new monitoring stack is located at different URLs.
- N/A
> [tmpnet] Update to use new monitoring urls (*-poc)

- accounts/keystore/keystore_test.go
- metrics/sample_test.go
- plugin/evm/gossiper_eth_gossiping_test.go
- plugin/evm/syncervm_test.go
- scripts/build_test.sh
- scripts/known_flakes.txt
I suggest that we take this approach to handling flakey tests.
I dislike our current situation:
- We have some tests that are important and we don't want to disable them, so we re-run the CI,
- We have some tests that we previously disabled and then subsequently they degraded from flakey -> failing tests without us noticing.
One downside of this PR is that CI may sometimes take longer (20m instead of 10m), as this runs tests that we know are flakey more often. So I am open to a smaller change, leaving the skipped tests as such, which would at least fix the first issue described above.
Example of the retry happening (this PR):
https://github.com/ava-labs/subnet-evm/actions/runs/10517836822/job/29142677042?pr=1305
> suggested for ci: re-run tests if failures are flakes

- accounts/keystore/keystore_test.go
- metrics/sample_test.go
- plugin/evm/gossiper_eth_gossiping_test.go
- plugin/evm/syncervm_test.go
- scripts/build_test.sh
- scripts/known_flakes.txt
Too much shell quoting makes it not work when you run it with NO_RACE=1
For the other PR that got merged with its changes, this is an example showing it works:
https://github.com/ava-labs/subnet-evm/actions/runs/10533951904/job/29190820267?pr=1304
> ci: fix NO_RACE + CI re-run on timeouts or fails of known flakes

- scripts/known_flakes.txt
Adds unrelated test failures from https://github.com/ava-labs/subnet-evm/actions/runs/10570009056/job/29283789250?pr=1311
Not sure if we should also add TestT8n from that run, but it seems the timeout in the other test is causing that so I didn't add it for now.
> Add observed flakes

- .github/CODEOWNERS
Adding the team alias to test.
If it works and others agree we can remove the individuals after
> add team alias to codeowners

- .github/workflows/tests.yml
- scripts/build_docker_image.sh
- scripts/constants.sh
- scripts/tests.build_docker_image.sh
A recent failure of post-merge image build suggested the need for a pre-merge sanity check to avoid unintentionally merging changes that break the image build.
Adds a new pre-merge CI job and test script to validate that the subnet-evm docker image can be built.
Locally and CI
N/A
> [ci] Validate image build

- go.mod
- go.sum
- precompile/contracts/warp/predicate_test.go
- precompile/contracts/warp/signature_verification_test.go
- scripts/versions.sh
- warp/validators/state_test.go
Seems the mock was moved to `validatorsmock`
> Bump avago master

- core/blockchain.go
- core/test_blockchain.go
After calling Reject the block is removed from the db. So the return value of HasBlock should be consistent with the DB, so we should invalidate the cache entry when we reject a block.
Also removed some unused code
See above
CI (added check for expected HasBlock behavior to test with reject)
N/A
> blockchain: Fix blockCache for rejected blocks

- core/blockchain.go
- core/state_transition.go
- core/txindexer.go
There is a potential race between txindexer and state sync (ResetToStateSyncedBlock/repairTxIndexTail), where reading can occur before repairTxIndexTail (which can increment the tail) and txindexer can work on an outdate tail (less than actual). 
Uses txindexer's `run` function after grabbing lock and then do the actual db read for tail for `run`. 
Not sure how to test this race
no need
> Tail lock revisited

- peer/network.go
- peer/stats/stats.go
The code is already removed so let's also remove it from the comments.
> nit: peer/network.go: remove refs to cross chain in comments

- scripts/build_antithesis_images.sh
- scripts/build_docker_image.sh
- scripts/constants.sh
- scripts/lib_avalanchego_clone.sh
- scripts/tests.build_docker_image.sh
https://github.com/ava-labs/subnet-evm/pull/1318 added image build validation, but only included support for testing against published avalanchego versions. Since subnet-evm CI frequently needs to target unmerged avalanchego commits, this oversight can break CI for version bump PRs. 
Updates the test to build the avalanchego image locally if it cannot be pulled. The logic that maintained the local avalanchego clone was extracted from the antithesis test script for reuse in the image build test script.
CI validates against regression, and the changes in this PR were validated by rebasing the changes against [the latest bump PR](https://github.com/ava-labs/subnet-evm/pull/1348) that targets an unmerged avalanchego commit and confirming that the test still passed.
Code comments.
> [testing] Fix image build validation for unmerged avalanchego commit

- scripts/build_test.sh
- scripts/known_flakes.txt
the ubuntu CI doesn't have `dos2unix` installed, so we can use sed instead
> fix ci: linux ci doesn't have dos2unix

- params/config.go
Similar to coreth: https://github.com/ava-labs/coreth/pull/663/files
Adds eth equivalent timestamps to avalanche chain configs
CI
N/A
> set timestamps in chain config

- core/genesis.go
- params/config_extra.go
See 	https://github.com/ava-labs/coreth/pull/667 for context
> fix setting eth upgrades in genesis storedcfg

- .github/workflows/bench.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- Dockerfile
- README.md
- accounts/abi/bind/bind_test.go
- accounts/abi/bind/precompilebind/precompile_bind_test.go
- go.mod
- go.sum
- params/config.go
- params/network_upgrades_test.go
- plugin/evm/vm_test.go
- scripts/versions.sh
- utils/snow.go
This is the base branch for uptime tracking module. The base branch depends on a non-merged AvalancheGo PR here https://github.com/ava-labs/avalanchego/pull/3346.
This PR should not be merged until we have a corresponding release in AvalancheGo
> uptime: update avalanchego dep branch

- miner/worker.go
Fixes tracking env tx size. 
Adds appended tx size to env.size
We don't have any worker tests.
no need
> track env size

- plugin/evm/vm.go
Close the rpc handlers to wait for in-flight rpc requests before calling eth.Stop which closes chaindb, as rawdb package doesn't propagate err correctly this can lead to panics during shutdown.
Explicitly calls .Stop for the rpc servers created
CI
N/A
> stop RPC servers in shutdown

- internal/debug/flags.go
Is no longer supported in go1.23 and is breaking antithesis build now for some reason
We already removed it in coreth
> remove memsize

- cmd/evm/internal/t8ntool/execution.go
- cmd/evm/runner.go
- core/blockchain.go
- core/chain_makers.go
- core/genesis.go
- core/state/state_test.go
- core/state/statedb.go
- core/state/statedb_fuzz_test.go
- core/state/statedb_test.go
- core/txpool/blobpool/blobpool_test.go
- eth/api_debug_test.go
- eth/state_accessor.go
- tests/state_test_util.go
- triedb/database.go
- triedb/hashdb/database.go
This provides better alignment with upstream code, avoiding passing an extra boolean to statedb.Commit and avoids an additional triedb backend method.
Still considering whether we can avoid the concurrent use of the triedb ref. counting entirely
Removes UpdateAndReferenceRoot in favor of a triedb backend (hashdb) option that references root when Update is called.
CI
N/A
> use triedb config for reference root

- README.md
The link to https://docs.avax.network/learn/virtual-machines is stale
Edited README.md
CI
> Fix stale link

- examples/sign-uptime-message/main.go
- plugin/evm/service.go
- plugin/evm/validators/locked_state_reader.go
- plugin/evm/validators/noop_state.go
- plugin/evm/validators/state.go
- plugin/evm/validators/state_test.go
- plugin/evm/validators/validator.go
- plugin/evm/vm.go
- plugin/evm/vm_validators_state_test.go
- warp/messages/payload.go
- warp/verifier_backend_test.go
* Adds a example for uptime warp msg signing
* Adds `IsSoV` and `weight` fields to validators 
Added e2e test
should document whole `GetCurrentValidators` API
> Uptime validation nits

- plugin/evm/client.go
- plugin/evm/service.go
This pull request introduces several changes to the `plugin/evm` package, primarily focusing on adding support for retrieving current validators and modifying the structure of the `CurrentValidator` type. The key changes are grouped into two themes: adding functionality and modifying data structures.
* Added the `GetCurrentValidators` method to the `Client` interface and its implementation in the `client` struct in `plugin/evm/client.go`. This method allows fetching the current validators. [[1]](diffhunk://#diff-f2ee9b6048cfd95ed277b400ea49d3ab7eaf30e8d033cdb0b6c7cfca9cae336cR27-L46) [[2]](diffhunk://#diff-f2ee9b6048cfd95ed277b400ea49d3ab7eaf30e8d033cdb0b6c7cfca9cae336cR78-R84)
* Updated the `CurrentValidator` struct in `plugin/evm/service.go` to replace `StartTime` with `StartTimestamp` …
> Use startimestamp

- plugin/evm/client.go
- plugin/evm/service.go
- plugin/evm/validators/state/interfaces/state.go
- plugin/evm/validators/state/state.go
`getCurrentValidators` in Platform VM API returns uptime percentage. This PR changes the uptime seconds to uptime percentage in `GetCurrentValidators` API to keep the consistency between APIs. It also adds NodeID filtering.
* [`plugin/evm/client.go`](diffhunk://#diff-f2ee9b6048cfd95ed277b400ea49d3ab7eaf30e8d033cdb0b6c7cfca9cae336cL27-R28): Modified the `GetCurrentValidators` method to accept `nodeIDs` as a parameter, allowing for filtered queries. [[1]](diffhunk://#diff-f2ee9b6048cfd95ed277b400ea49d3ab7eaf30e8d033cdb0b6c7cfca9cae336cL27-R28) [[2]](diffhunk://#diff-f2ee9b6048cfd95ed277b400ea49d3ab7eaf30e8d033cdb0b6c7cfca9cae336cL80-R85)
* [`plugin/evm/service.go`](diffhunk://#diff-42f3e9fd1f7cfff775643d1bad698671c0a34b8e3d3e5ab867626fcc0fa6fb8fR7-R21): Introduced …
> use nodeID filter and uptimePerc

- README.md
- go.mod
- go.sum
- scripts/versions.sh
This pull request includes updates to version references in multiple files to ensure consistency and correctness across the project.
Version updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L33-R33): Updated the version reference for `v0.6.12` to include `v1.12.0-fuji` alongside `v1.11.13` for better clarity.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L8-R8): Changed the version of `github.com/ava-labs/avalanchego` from `v1.11.13-rc.1` to `v1.11.13` to reflect the stable release.
* [`scripts/versions.sh`](diffhunk://#diff-c275e70e7b0f41a73996876c584ca0336077f3ce442f2a9b9088ca351f7d9a0eL7-R7): Updated the `AVALANCHE_VERSION` from `v1.11.13-rc.1` to `v1.11.13` to match the stable …
> bump avago to v1.11.13

- .github/workflows/release.yml
- .goreleaser.yml
Seems goreleaser made some breaking changes or something in our builders changed.
In any case the new way seems to succeed.
> specify arm64 version in goreleaser

- .github/workflows/tests.yml
This pull request includes updates to the `.github/workflows/tests.yml` file to ensure the use of a newer version of the `run-monitored-tmpnet-cmd` action.
Workflow updates:
* Updated the `run-monitored-tmpnet-cmd` action from version `v1.11.11-monitoring-url` to `v1.11.13` for the Warp E2E Tests job.
* Updated the `run-monitored-tmpnet-cmd` action from version `v1.11.11-monitoring-url` to `v1.11.13` for the E2E Load Tests job.
> bump to latest avago

- core/blockchain.go
- core/state/statedb.go
- core/state/trie_prefetcher.go
- core/state/trie_prefetcher.libevm.go
- core/state/trie_prefetcher_extra_test.go
- core/state/trie_prefetcher_test.go
- libevm/sync/sync.go
- miner/worker.go
If you use a shared `BoundedWorkers` across all tries[^1] then it's sufficient[^2][^3] to block on `StateDB.StopPrefetcher()` or on `triePrefetcher.close()` when you don't have a full DB.
[^1]:  I think this is what we should be doing as it's the point of `BoundedWorkers`. It's also what your original implementation had too.
[^2]:  There was a bug in my ordering of the `defer` statements at the top of `subfetcher.loop()`. I fixed it here; on my libevm branch I also added a test to prove that `StopPrefetcher()` blocks until `WorkerPool.Wait()` returns.
[^3]: I (wrongly) assumed that `BoundedWorkers` would allow extra work while `Wait()`ing.
> refactor: block on `StopPrefetchers()` instead of `cleanup`

- core/state/pruner/pruner.go
- miner/worker.go
- plugin/evm/vm_test.go
- sync/statesync/trie_sync_stats.go
- warp/aggregator/aggregator_test.go
fix problematic const name and some typos in comment
No need.
No
No need.
> chore: fix problematic const name and some typos in comment

- precompile/contract/interfaces.go
- rpc/types.go
fix some function names in interface comment
No need
No
No
> chore: fix some function names in interface comment

- eth/tracers/js/tracer_test.go
- eth/tracers/logger/access_list_tracer.go
- internal/ethapi/transaction_args.go
- rpc/handler.go
fix some function names in comment
No need
No need
No need
> chore: fix some function names in comment

- consensus/dummy/README.md
- precompile/contracts/warp/README.md
This PR addresses minor typographical issues in the documentation, improving clarity and adherence to grammatical standards.
- **File: `consensus/dummy/README.md`**
- Added a hyphen to correctly format "10-second interval."
- **File: `precompile/contracts/warp/README.md`**
- Updated "eg." to the proper abbreviation "e.g." (for example).
These are documentation changes that do not impact code execution. The changes were reviewed for correctness and clarity.
No additional documentation is needed.
No updates to `RELEASES.md` are required as this PR does not introduce functional changes.
> Fix Typos in Documentation

- .github/workflows/bench.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
So we use the Go version specified, not the latest one.
See https://github.com/actions/setup-go?tab=readme-ov-file#check-latest-version
Sibling version of https://github.com/ava-labs/coreth/pull/722
Removed `check-latest: true` in Go setup action
CI passing
No
No
> chore(ci): remove `check-latest: true` to ensure the specified Go version

- .github/workflows/tests.yml
- triedb/pathdb/database_test.go
Adds changes from Coreth
Cherry-picks differences
UT
No
No
> Coreth sync

- README.md
the old link was giving me an error
> docs(readme): fix link to Avalanche documentation

- plugin/evm/vm_test.go
deprecated avalanchego keystore that was removed in https://github.com/ava-labs/avalanchego/pull/3657
only unittest is affected
unittest
no
no
> deprecate avago keystore

- accounts/abi/bind/bind.go
- accounts/abi/bind/bind_extra.go
- accounts/abi/bind/template.go
- cmd/abigen/namefilter.go
- cmd/abigen/namefilter_test.go
- triedb/pathdb/database_test.go
- utils/numbers.go
Includes changes to the `accounts/abi/bind` package, focusing on renaming types and functions for consistency with upstream and coreth by moving some functionality to a new file.
The most important changes include renaming `TmplContract`, `TmplMethod`, and `TmplStruct` to `tmplContract`, `tmplMethod`, and `tmplStruct`, respectively, and moving the `BindHook` function and related types to a new file `bind_extra.go`.
This makes our modifications much clearer.
Some additional cosmetic changes are also reduced.
> refactor: align accounts/abi/bind with coreth+upstream

- core/txpool/legacypool/legacypool.go
https://github.com/ava-labs/coreth/pull/741
This pull request includes several changes to the `core/txpool/legacypool/legacypool.go` file, primarily focused on simplifying the code by removing unnecessary locks and improving variable declarations.
Code simplification:
* Removed the `currentStateLock` mutex from the `LegacyPool` struct and all associated lock/unlock calls, as it is no longer needed for concurrent access. [[1]](diffhunk://#diff-3b03ebf997a1699ce8e84a53a4b3981e403e74e2f90128eb188ad4226703970cL233-L235) [[2]](diffhunk://#diff-3b03ebf997a1699ce8e84a53a4b3981e403e74e2f90128eb188ad4226703970cL691-L693) [[3]](diffhunk://#diff-3b03ebf997a1699ce8e84a53a4b3981e403e74e2f90128eb188ad4226703970cL1506-L1508) [[4]](diffhunk://#diff-3b03ebf997a1699ce8e84a53a4b3981e403e74e2f90128eb188ad4226 …
> remove current state lock

- .github/workflows/release.yml
A bug is introduced in 2.6.0 that ignores the environment overrides.
> pin goreleaser v2.5.1

- consensus/dummy/consensus.go
- consensus/dummy/consensus_test.go
- consensus/dummy/dynamic_fees.go
- consensus/dummy/dynamic_fees_test.go
- utils/numbers.go
- utils/numbers_test.go
Cherry picks following PR from Coreth and syncs coreth master up to [a9437e4](https://github.com/ava-labs/coreth/commit/a9437e4)
https://github.com/ava-labs/coreth/pull/794
https://github.com/ava-labs/coreth/pull/797
Added relevant UTs for subnet-evm fee configs.
No
No
> Dynamic fees cleanup

- RELEASES.md
- plugin/evm/validators/interfaces/interfaces.go
- plugin/evm/validators/manager.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
`snow.Context.Lock` provided by AvalancheGo(rpcchainvm) is not reliable for engine calls. Validator manager should not depend on that, and rather hold the ctx itself.
Moves ctx lock management to validators manager, hold ctx lock in `Connected`, `Disconnected`
UT, locally
No
updated
> use ctx in validatorsManager

- .github/workflows/release.yml
Release action checks out repo to `subnet-evm` path. Go.mod path was wrong in release.yml.
Fixed go.mod file path
Manual CI trigger
No
No
> fix go mod path

- plugin/evm/validators/state/state.go
This PR removes an impossible error case from state.WriteState.
The switch case was covering three states:
```golang
switch variable ( of type bool ) {
case false:
...
case true:
...
default:
<generate error>
```
Given that a boolean can be either true or false, and nothing else, the default path is not possible.
By the virtue of the error, this code change is not testable.
no.
no.
> eliminate an impossible error case from state.WriteState

- cmd/simulator/README.md
The readme is mentioning an incorrect flag
Replace it with the correct flgag
n/a
n/a
No
> [simulator] Fix wrong flag name in readme

- scripts/versions.sh
Previously it was necessary to manually maintain the avalanchego version in versions.sh. Now the version is automatically detected via go modules.
- updates versions.sh to automatically determine the version/SHA from go module
- CI
- Manually checked the version used matched the go module version when invoking `bash -x scripts/build.sh`
N/A
N/A
> Simplify avalanchego version maintenance

- cmd/evm/internal/t8ntool/transition.go
- consensus/dummy/consensus.go
- consensus/dummy/dynamic_fees.go
- consensus/dummy/dynamic_fees_test.go
- core/blockchain_reader.go
- core/chain_makers.go
- core/state_processor_test.go
- core/txpool/blobpool/blobpool_test.go
- core/txpool/legacypool/legacypool.go
- eth/gasprice/gasprice.go
- miner/worker.go
Cherry picks following PR from Coreth
https://github.com/ava-labs/coreth/pull/802
https://github.com/ava-labs/coreth/pull/804
> Support upgrades in dynamicfees

- plugin/evm/admin.go
- plugin/evm/service.go
- plugin/evm/validators/interfaces/interfaces.go
- plugin/evm/validators/locked_reader.go
- plugin/evm/validators/manager.go
- plugin/evm/validators/state/state.go
- plugin/evm/vm.go
- plugin/evm/vm_validators_test.go
- warp/verifier_backend_test.go
`snow.Context.Lock` is deprecated and rpchainvms should not depend on it. This PR changes ctx locks to chainLocks and updates validator manager.
This pull request includes several changes to improve thread safety by replacing the use of `vm.ctx.Lock` with `vm.chainLock` across various files. Additionally, it introduces a new `lockedReader` type to handle validator operations with locking.
* [`plugin/evm/admin.go`](diffhunk://#diff-33ca639e424bc2d90f5f568847a93aaef9e1f447d98a671c7f565983e8f22db7L33-R34): Replaced `vm.ctx.Lock` with `vm.chainLock` in methods `StartCPUProfiler`, `StopCPUProfiler`, `MemoryProfile`, and `LockProfile`. [[1]](diffhunk://#diff-33ca639e424bc2d90f5f568847a93aaef9e1f447d98a671c7f565983e8f22db7L33-R34) [[2]](diffhunk://#diff-33ca639e424bc2d90f5f568847a93aaef9e1f447d98 …
> remove ctx locks and use chain locks

- .github/workflows/bench.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/tests.yml
Adds merge group actions to ci workflows.
This pull request adds a new event type to the GitHub Actions workflows to trigger the workflows when checks are requested for a merge group. This change ensures that the workflows run in response to specific events related to merge groups.
Changes to GitHub Actions workflows:
This pull request includes updates to multiple GitHub Actions workflow files to add a new event type for triggering workflows. The changes ensure that workflows can be triggered when checks are requested for a merge group.
Updates to GitHub Actions workflows:
* [`.github/workflows/bench.yml`](diffhunk://#diff-a5e740be96415373789689f814583e93ff2a8f05eae6481e94505fd6cb6bc6a7R6-R7): Added `merge_group` event type with `checks_requested` to trigger the workflow.
* …
> chore(ci): add merge groups

- README.md
- RELEASES.md
Updates releases.md and avalanchego compatibilitity
> update after 0.7.2 release

- predicate/predicate_slots.go
remove redundant word in comment
> chore(predicate): fix typo in `PreparePredicateStorageSlots` comment

- RELEASES.md
- params/network_upgrades.go
- params/network_upgrades_test.go
Fortuna is currently activated on Fuji. We have no corresponding Subnet-EVM version as Fortuna have no effect on subnet-evm networks. Therefore we should keep the default as nil so that it won't break when nodes update to any newer Subnet-EVM version. 
Fortuna is still kept as a defined upgrade in Subnet-EVM to reduce diff between Coreth. 
* Adds a nil default for Fortuna
* returns nil error if default ts is nil in `verifyWithDefault`.
Added UT
Not probably
Updated
> add fortuna default as nil

- go.mod
- go.sum
The avalanchego version got bumped too high compared to what the master branch is using.
I reworked the avalanchego libevm branch (the subnet-evm specific one) to be based on what subnet-evm avalanchego version is on the master branch.
Change go.mod
> chore(deps): use libevm avalanchego based on `v1.12.3-rc.1.0`

- plugin/evm/service.md
Supercedes https://github.com/ava-labs/subnet-evm/pull/1471
Stores local API documentation with subnet-evm `service.go`. Subnet-EVM maintainers can update this file whenever there is a change to the API and changes will be reflected in the docs upon the following build.
@federiconardelli7
Adds `service.md` compatible with docs framework.
NA
Yes?
No
> docs(plugin/evm): add local API docs to be pulled by Docs `remote-content.mts`

- core/evm.go
- core/rawdb/accessors_metadata.go
- precompile/allowlist/allowlist.go
- precompile/contracts/rewardmanager/contract.go
- sync/statesync/code_syncer.go
- utils/metered_cache.go
EDIT: see [below comment](https://github.com/ava-labs/subnet-evm/pull/1506#issuecomment-2747346312), this "typo-accumulation-branch" approach is to be abandoned. Note the 3 commits of this branch will be preserved in the master branch, similarly if they would be merged individually in master directly.
---
Previous rationale:
We get a lot of typo fix PRs on this repository, and having tens of "fix typos" 2-lines commits in the master branch does some git history pollution as well as occupies the merge queue for not much reason.
This PR accumulates pull requests suggesting typo fixes into one PR to be squashed in a single co-authored commit
> chore(all): fix different typos

- precompile/contracts/warp/README.md
Documentation only PR to clarify the semantics of the self signing optimization for Warp verification for L1s versus Subnets.
> [documentation] Differentiate between L1 and Subnet self-signing optimization cases

- .github/workflows/tests.yml
- go.mod
- go.sum
We want to create a release tag v0.7.3 using the v0.12.3 based avalanchego version, and will re-upgrade the avalanchego version after that with #1536 
This reverts commit 10aac5f734459f545172fd598d6ddd47d7d23f0b.
> Revert "chore(deps): bump avalanchego to v1.13.1-0.20250321174807-6c72dfc4254a (#1516)"

- .github/workflows/release.yml
- .goreleaser.yml
Fix issue when there is an RC tag and a non-RC tag pointing to the same commit
- Use workflow event ref .goreleaser.yml config
- Use goreleaser git option `prerelease_suffix: "-rc"`
v0.7.3 release goreleaser action run
> fix(cd): goreleaser picks non-rc tag and uses workflow config

- core/genesis.go
- core/genesis_extra_test.go
- params/extras/config.go
- params/extras/config_test.go
- params/extras/precompile_config_test.go
- params/extras/precompile_upgrade_test.go
Critical fixes **only** from review on #1501 
Minor changes can be applied in #1552
> fix(all): critical fixes to the libevm branch

- RELEASES.md
- plugin/evm/vm.go
- plugin/evm/vm_test.go
Mempool was not initialized correctly from the blockchain state and correct minfee was not applied.
Reads the minfee from the state and then sets the mempool minfee accordingly
added UT
No
Yes
> set minfee from state on mempool init 

- .github/workflows/tests.yml
Mirror of [1028](https://github.com/ava-labs/coreth/pull/1028). [Windows is not supported anymore](https://github.com/ava-labs/avalanchego/pull/4031) and the Windows tests take a lot of time to run which is both annoying and costs money. As requested by @ceyonur. 
This is a very small change which removes the Windows option from the CI. 
No 
No
> remove Windows CI tests

- coreth-version.txt
- latest-coreth-commit.txt
Updated latest coreth commit to 3cf977c219ff46951c6b0a2227d69262a0a3038a sycned with https://github.com/ava-labs/subnet-evm/commit/53da01769617d1df42243d7c818a2399f70edf34
> update latest synced coreth commit

- docs/releasing/README.md
The releasing readme incorrectly lists what tag should be used to tag release candidates. This should be fixed to avoid confusion. (Not like I would know....)
> Change realeasing/README.MD tag instructions to $VERSION_RC from $VERSION

- .github/workflows/tests.yml
- README.md
- RELEASES.md
- compatibility.json
- go.mod
- go.sum
- plugin/evm/version.go
The release candidate for `subnet-evm v0.7.7`
> chore: release v0.7.7-rc.0

- .github/workflows/tests.yml
- Taskfile.yml
- latest-coreth-commit.txt
- scripts/update_avalanchego_version.sh
Ports the related changes from ava-labs/coreth#1003, as well as ava-labs/coreth#1064 and ava-labs/coreth#1066
Adds debug printing back, moves github token in
In coreth
No
No
> ci: Add GH token

- RELEASES.md
- docs/releasing/README.md
- The wrong branch name is used in the merge command
- `--delete-branch` can not be used without an error when a merge queue is enabled
- 0 is not a valid amount of Dispatch or Echo to send (must be >0 as Core wallet will tell you)
- Make numbering more clear
> chore: Fix releases guide 

- latest-coreth-commit.txt
- sync/client/leaf_syncer.go
- sync/statesync/state_syncer.go
Syncs https://github.com/ava-labs/coreth/pull/1058
Note that as `subnet-evm` does not contain the `plugin/evm/atomic/` package, this sync is limited to aligned variable names to threads. There are no functional changes in this PR.
> sync: coreth PR #1058: update numThreads to numWorkers

- go.mod
- go.sum
- latest-coreth-commit.txt
- triedb/firewood/database.go
The most recent version of Firewood has a fix for the concurrency bug (see the one code change)
Mirrors ava-labs/coreth#1134
Update go.mod and go.sum
CI - but also ran with race checker locally to ensure that the race condition no longer exists
No
No
> perf: upgrade Firewood
