ava-labs/subnet-evm

- scripts/versions.sh
This PR starts the release cycle for v0.2.2.
> Start v0.2.2 release cycle

- README.md
- contract-examples/contracts/ExampleTxAllowList.sol
- contract-examples/hardhat.config.ts
- contract-examples/scripts/deployExampleTxAllowList.ts
- contract-examples/test/ExampleTxAllowList.ts
- core/state_processor_test.go
- core/state_transition.go
- core/stateful_precompile_test.go
- core/tx_pool.go
- params/config.go
- plugin/evm/vm_test.go
- precompile/params.go
- precompile/tx_allow_list.go
This PR adds a tx allow list stateful precompile.
> Add tx allow list

- .github/workflows/e2e.yml
- README.md
- scripts/parser/main.go
- scripts/run.sh
- tests/e2e/e2e_test.go
> scripts/run.sh: add back "parser/main.go" commands

- .github/workflows/lint-tests-release.yml
- README.md
- go.mod
- go.sum
- plugin/evm/client.go
- plugin/evm/database.go
- scripts/run.sh
- scripts/versions.sh
> Bump AvalancheGo Version

- accounts/abi/bind/backends/simulated.go
- chain/subnet_evm.go
- chain/subscribe_accepted_heads_test.go
- chain/subscribe_block_logs_test.go
- core/blockchain.go
- core/blockchain_reader.go
- core/blockchain_repair_test.go
- core/blockchain_snapshot_test.go
- core/blockchain_test.go
- core/bounded_buffer.go
- core/rawdb/accessors_metadata.go
- core/rawdb/schema.go
- core/state_manager.go
- core/state_manager_test.go
- core/test_blockchain.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/tracers/api_test.go
- peer/network.go
- peer/stats/stats.go
- plugin/evm/config.go
- plugin/evm/service.go
- plugin/evm/vm.go
- trie/committer.go
- trie/database.go
- trie/database_test.go
- trie/iterator_test.go
- trie/secure_trie.go
- trie/trie.go
adds changes between coreth 0.8.10-rc.5 <> 0.8.12, without following fastsync-related commits:
1- https://github.com/ava-labs/coreth/commit/90dafe95d2ba401096d1fb9dbc613471926fed93
2- https://github.com/ava-labs/coreth/commit/9fb7a2025a20f3a5546683571f1066cae932457c
3-https://github.com/ava-labs/coreth/commit/5a65c0b948bc81da3a9d68e688217ab3fba7d91d
4-https://github.com/ava-labs/coreth/commit/ae8b4a1b10ec0265b9f01a175f0ce229337b8523
5- https://github.com/ava-labs/coreth/commit/2beeb12dc8625f1e08d6bf16e79e45820dc99308
6-https://github.com/ava-labs/coreth/commit/36b069f5b46d8fd97af40ad97caba4fbb3eddd9c
7-https://github.com/ava-labs/coreth/commit/52d34c61eccbe0bcf94a00a8c2c575a7c8274574
8-https://github.com/ava-labs/coreth/commit/16aace50a7ad937253c75a451dd36673c9754b04 …
> [AV-1753] merge coreth 0.8.12

- .github/ISSUE_TEMPLATE/feature_spec.md
Adds a template for design specs
> Issue template for design spec

- core/stateful_precompile_test.go
- params/config.go
- precompile/contract.go
- precompile/stateful_precompile_config.go
minor improvements for comments and type checks
> nit: improve some precompile comments, type checks

- core/genesis.go
- core/rawdb/accessors_metadata.go
Sketched the idea of merging Read/Write Upgrade with Chain in rawdb.
Seems this leaves less room for potential mistakes in the future though I also don't mind the code as is with functions in rawdb having less responsibilities
> merge (Read,Write) UpgradeConfig  w/ ChainConfig

- plugin/evm/vm.go
Fixes #203 test by setting etherbase address from `vm.ethConfig.Miner.Etherbase`
> Set ether base fix

- plugin/evm/config.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
Adds FeeRecipient config tests.
This should be failing since we currently are changing the etherbase to blackhole forcefully in the VM init.
> Set ether base regression

- internal/ethapi/api.go
This is intended to be used by API providers to better ratelimit users by introducing a new version of eth_call that provides the gas used by a call.
> CallDetailed

- internal/ethapi/api.go
This is to avoid hardcoding error codes in the api worker
> Expose eth_call error code

- core/blockchain.go
- core/state/trie_prefetcher.go
This PR adds the logs from these two PRs:
- https://github.com/ava-labs/coreth/commit/ea26282649311e5f3ac8893ef780653a99683973#
- https://github.com/ava-labs/coreth/commit/50aacfd1005c4023950b3b8c2dbe87c1f6e86363
> Add statedb error and prefetcher logs

- scripts/lint_allowed_geth_imports.sh
This PR adds a comment to the geth pkg import linting script.
> Add comment to geth pkg import linting script

- networks/README.md
- networks/mainnet/432204/README.md
- networks/mainnet/432204/contracts.json
- networks/mainnet/432204/genesis.json
Provides information on Dexalot Mainnet Subnet
> Dexalot Mainnet Subnet info

- core/tx_pool.go
Signed-off-by: Gyuho Lee <gyuho.lee@avalabs.org>
> core/tx_pool: remove unused "TxStatusIncluded"

- cmd/simulator/go.mod
- cmd/simulator/go.sum
- core/blockchain.go
- core/blockchain_test.go
- go.mod
- go.sum
- plugin/evm/vm.go
- Remove the minimum enforced trie clean rejournal interval of 1 minute
- Add unit test to ensure that trie clean rejournaling generates files correctly
> Save cache periodically test

- core/blockchain.go
- core/state/trie_prefetcher.go
- trie/database.go
Replaces: #331 (less invasive)
> Improve Cache Performance

- compatibility.json
- plugin/evm/version.go
- scripts/versions.sh
This PR starts the v0.4.4 release cycle.
> Start v0.4.4 release cycle

- contract-examples/hardhat.config.ts
- contract-examples/local_rpc.example.json
adds custom chain ID to `local_rpc.json`
> add custom chain ID to config.ts

- README.md
- accounts/abi/bind/precompile_template.go
- params/precompile_config.go
- precompile/contract_deployer_allow_list.go
- precompile/contract_native_minter.go
- precompile/fee_config_manager.go
- precompile/stateful_precompile_config.go
- precompile/tx_allow_list.go
adds logs to activating/deactivating upgrades
> add prints to activating precompiles

- .github/CODEOWNERS
This PR fixes the wildcard pattern used in the CODEOWNERS file.
> Fix codeowners wildcard pattern

- core/state_manager.go
Removes an unneeded type annotation.
> nit: remove unneeded type annotation

- plugin/evm/config.go
Address @ceyonur's comments on coreth PR:
> nit: can we group them together and put // TxPool Settings above?
Minor updates.
Unit tests.
> Minor format updates to plugin/evm configurations

- compatibility.json
- plugin/evm/version.go
- scripts/versions.sh
This PR starts the v0.4.6 release cycle
> Start v0.4.6 release cycle

- params/config_test.go
adds a regression test for the IsDisabled case in AvalancheRules
> precompiles: adds a regression test for the IsDisabled case in AvalancheRules

- README.md
Updates AvalancheGo compatibility for v1.9.9
Updates README
CI
n/a
> Update AvalancheGo compatibility

- compatibility.json
- plugin/evm/version.go
- scripts/versions.sh
This PR starts the v0.4.10 release cycle.
> Start v0.4.10 release cycle

- accounts/abi/bind/precompilebind/precompile_contract_template.go
Adds a whitespace before long comment 
Locally generated
> add whitespace

- README.md
- compatibility.json
- core/blockchain.go
- core/vm/contracts.go
- go.mod
- go.sum
- peer/network.go
- plugin/evm/factory.go
- plugin/evm/version.go
- scripts/versions.sh
- sync/client/leaf_syncer.go
- sync/statesync/trie_segments.go
This PR starts porting the recent coreth changes to subnet-evm
CI
No documentation necessary for these changes
> Start coreth migration

- peer/network.go
- precompile/contracts/warpmessenger/contract.go
- warp/backend.go
- warp/handlers/signature_request.go
> Teleporter demo debug

- accounts/abi/abi.go
- trie/stacktrie.go
Follows upstream https://github.com/ethereum/go-ethereum/pull/26914
Adds err checks
CI
No changes
> trie, accounts/abi: nits: adds err checks

- eth/backend.go
- plugin/evm/vm.go
This PR adds more detailed logs on shutdown.
> Add more logs on shutdown

- params/state_upgrade_test.go
Renames stateupgrade test file.
> rename state upgrade test

- plugin/evm/gossiper.go
Fix godoc.
Doc update.
N/A
N/A
> plugin/evm: fix godoc typo

- README.md
Fix the broken path in the `README`.
> Fix broken path in README.

- core/bench_test.go
Fixes the chain insert benchmarks in the core package.
Sets the coinbase address so that the benchmarks pass with the `params.TestChainConfig`.
Running the benchmarks for the changed file locally, which failed previously.
na
> Fix core benchmarks

- contracts/package-lock.json
- contracts/package.json
This PR removes unused ethereum-waffle and ethereumjs-tx packages.
> Remove unused ethereum-waffle and ethereumjs-tx pkgs

- core/bench_test.go
- core/predicate_check.go
- core/predicate_check_test.go
- core/state/statedb.go
- core/state_transition.go
- core/tx_pool.go
- core/vm/interface.go
- precompile/allowlist/test_allowlist.go
- precompile/contract/interfaces.go
- precompile/precompileconfig/config.go
- precompile/testutils/test_precompile.go
- precompile/testutils/test_predicate.go
This PR adds support for predicate gas.
Enables precompiles to create a predicate that charges gas within `IntrinsicGas(...)`.
CI
na
> Add support for predicate gas

- tests/utils/command.go
- tests/utils/subnet.go
Improve tests based on feedback from https://github.com/ava-labs/subnet-evm/pull/712
> Improve tests

- core/blockchain_test.go
> mark TestTransactionIndices as flaky

- .github/workflows/bench.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile
- README.md
- scripts/build.sh
> Bump min go version

- plugin/evm/block_builder.go
Reverts ava-labs/subnet-evm#783
> Revert "add debug log for dropped pending txs notifications"

- core/state_transition.go
- core/txpool/txpool.go
- core/vm/evm.go
- precompile/allowlist/allowlist.go
- precompile/allowlist/role.go
- precompile/allowlist/role_test.go
- precompile/allowlist/test_allowlist.go
- precompile/contract/contract.go
- precompile/contracts/feemanager/contract.go
- precompile/contracts/feemanager/contract_test.go
- precompile/contracts/nativeminter/contract.go
- precompile/contracts/nativeminter/contract_test.go
- precompile/contracts/rewardmanager/contract.go
- precompile/contracts/rewardmanager/contract_test.go
> use activation in precompile functions

- plugin/evm/vm_test.go
- plugin/evm/vm_upgrade_bytes_test.go
> remove unnecessary upgrade test

- consensus/dummy/consensus.go
- consensus/dummy/dynamic_fees.go
- params/config.go
- plugin/evm/block_verification.go
This PR adds support for extra data past the dynamic fee window. This is intended to be used by https://github.com/ava-labs/subnet-evm/issues/735
> Add DUpgrade extra data

- core/genesis.go
- core/genesis_test.go
This PR adds a regression test and fix for https://github.com/ava-labs/subnet-evm/issues/818.
> Fix persist upgrade bytes regression

- core/blockchain.go
Use the same calculation as coreth & more similar to upstream.
Current calculation is omitting reads from the total trie time
Copies the code from coreth
CI
N/A
> Align blockchain.go trie metrics with coreth

- accounts/abi/bind/precompilebind/precompile_bind_test.go
- accounts/abi/bind/precompilebind/precompile_config_test_template.go
Fixes test suite and adds gomock import to templ
Fixes actual test suite.
> import gomock in test templ

- tests/warp/warp_test.go
- warp/warp_client.go
- warp/warp_client_fetcher.go
Remove stuttering.
N/A
N/A
N/A
> rename WarpClient to Client

- .github/workflows/auto-generated-code-checker.yml
- .github/workflows/bench.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile
- README.md
- accounts/abi/bind/bind_test.go
- accounts/abi/bind/precompilebind/precompile_bind_test.go
- go.mod
- go.sum
- peer/network_test.go
- plugin/evm/vm.go
- scripts/build.sh
- scripts/versions.sh
- tests/utils/runner/network_manager.go
- warp/backend.go
Sync corresponding PR from Coreth: https://github.com/ava-labs/coreth/commit/0af32656d49e0e1eaaf8a9be50dcc8cbf6c6ec3f
> Bump avago rc

- .github/workflows/auto-generated-code-checker.yml
- .github/workflows/bench.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile
- README.md
- accounts/abi/bind/bind_test.go
- accounts/abi/bind/precompilebind/precompile_bind_test.go
- go.mod
- go.sum
- peer/network.go
- peer/network_test.go
- plugin/evm/vm.go
- scripts/build.sh
- scripts/versions.sh
- tests/utils/runner/network_manager.go
- warp/backend.go
Sync corresponding PR from Coreth: https://github.com/ava-labs/coreth/pull/326
> Fix hanging requests after Shutdown (#326)

- .github/workflows/auto-generated-code-checker.yml
- .github/workflows/bench.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile
- README.md
- accounts/abi/bind/bind_test.go
- accounts/abi/bind/precompilebind/precompile_bind_test.go
- go.mod
- go.sum
- peer/network.go
- peer/network_test.go
- plugin/evm/vm.go
- scripts/build.sh
- scripts/versions.sh
- tests/utils/runner/network_manager.go
- warp/backend.go
Syncs corresponding PR: https://github.com/ava-labs/coreth/pull/316
> Add SDK Router message handling (#316)

- warp/handlers/signature_request.go
Reduces duplicate code.
Self-explanatory.
Existing UT.
N/A
> reduce duplicate code in OnSignatureRequest

- x/warp/contract.go
- x/warp/contract_warp_handler.go
Solves https://github.com/ava-labs/subnet-evm/issues/903
Dropped code duplication
CI
No visible behaviour really changed, so no need to update docs
> removed code duplication

- plugin/evm/block.go
Addresses https://github.com/ava-labs/subnet-evm/issues/904
> Change from parsing predicate bytes to checking they equal expected value

- core/predicate_check.go
Reverts https://github.com/ava-labs/subnet-evm/pull/901/commits/f5b7b2a649f6bc5b5ff173390d488985799d6a4a and fixes UT: https://github.com/ava-labs/subnet-evm/actions/runs/6329646962/job/17190372894#step:6:31
> add early return

- warp/aggregator/aggregation_job.go
- warp/aggregator/aggregation_job_test.go
- fixes UT
- deterministic behavior for reaching max threshold
- improves logging by adding msgID
> nits: TestAggregateThresholdSignaturesOverMaxNeeded

- cmd/evm/internal/t8ntool/block.go
Pretty straightforward bugfix. 
Tests pass before and after.
> t8ntool: tiny bugfix for difficulty field

- core/evm.go
- plugin/evm/block.go
- predicate/predicate_bytes.go
- predicate/predicate_bytes_test.go
This PR fixes an incorrect error log parsing predicate bytes.
> predicate: fix predicate bytes incorrect error log

- accounts/abi/bind/bind.go
- accounts/abi/bind/precompilebind/precompile_bind_test.go
- accounts/abi/bind/precompilebind/precompile_event_template.go
- precompile/contract/utils.go
- precompile/contracts/rewardmanager/contract.go
- precompile/contracts/rewardmanager/contract_test.go
- precompile/contracts/rewardmanager/event.go
Follow up on: #961 
This adds a gas calculation function for events to the template and adds an example for reward manager precompile.
> Reward manager gas cost

- plugin/evm/service.go
> remove unnecessary locks

- .github/CODEOWNERS
Removes specific directories from codeowners file.
> remove specific folders

- peer/network.go
This PR downgrades p2p network logs from debug to trace.
With the added p2p SDK logs and increased network messages, the number of debug logs coming from the peer network package has become extremely large making debug logs significantly more difficult to parse through with minimal added information.
Downgrading these logs to `TRACE` keeps the information available if needed, but removes it from the debug level so that debug test logs provide more helpful output.
This PR also removes the `Connected` and `Disconnected` logs since there's no additional information and `Connected` and `Disconnected` events are already logged by AvalancheGo.
> downgrade p2p network logs from debug to trace

- README.md
- params/config.go
- params/precompile_upgrade_test.go
- params/state_upgrade_test.go
Fixes incorrect value in the string.
Shows pointer value (or nil) in the err string rather than showing memory address reference.
Added unit tests
We should create the same PR to upstream repos.
> fix pointers in err string

- precompile/precompileconfig/config.go
> Update Predicater interface comment

- accounts/abi/topics.go
- accounts/abi/topics_test.go
From: https://github.com/ethereum/go-ethereum/pull/28764
> fix negative bigint topics

- eth/state_accessor.go
- eth/tracers/api_test.go
Passes missing configs from StateAtNextBlock to StateAtBlock
> pass configs to StateAtBlock

- plugin/evm/message/codec.go
- plugin/evm/message/message_test.go
- sync/handlers/block_request.go
- sync/handlers/block_request_test.go
Fixes a bug related to large blocks in state sync
Takes the same fixes & tests applied to coreth
CI
N/A
> Fix large block requests in state sync

- contracts/package-lock.json
- contracts/package.json
Bumps npm package versions and subnet-evm-contracts. New package version will be published once this PR got merged.
Updates versions in package.json
CI should cover this.
> bump npm versions

- params/config.go
Fixes cancun release banner from avalanchego v1.11.0 to v1.12.0
> fix cancun banner release

- cmd/simulator/config/flags.go
- cmd/simulator/load/loader.go
- cmd/simulator/metrics/metrics.go
Improves metrics
Closes: #1092
> improve metrics

- README.md
- compatibility.json
- go.mod
- go.sum
- plugin/evm/version.go
- scripts/versions.sh
Prepares release for v0.6.1 with Avago 1.11.1
> bump versions

- cmd/precompilegen/template-readme.md
Adds event to precompile template readme
> add event to readme

- README.md
- compatibility.json
- plugin/evm/version.go
> bump version to v0.6.3

- .github/workflows/tests.yml
- .golangci.yml
Fixes linter + updates version
> skip pkg cache and update version

- peer/network.go
Mirrors https://github.com/ava-labs/coreth/pull/543/files
> Mark ourself as connected (#543)

- params/network_upgrades.go
Fixes string for nicer printout
> nit: fix spacing in config printout

- eth/tracers/api.go
> add missing overrides for api

- .github/workflows/bench.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- Dockerfile
- README.md
- compatibility.json
- go.mod
- go.sum
- plugin/evm/version.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
- scripts/versions.sh
Prepares for the next subnet-evm release v0.6.7
> Subnet evm 0.6.7

- README.md
Updates versions for v0.6.8 release
> bump versions for 0.6.8

- README.md
fixes wrong avalanchego support entry in readme
> fix readme avago entry

- plugin/evm/gossiper_eth_gossiping_test.go
https://github.com/ava-labs/subnet-evm/issues/1264
> fix TestMempoolEthTxsAppGossipHandling

- accounts/abi/bind/bind_test.go
- accounts/abi/bind/precompilebind/precompile_bind_test.go
- commontype/test_fee_config.go
- core/state/test_statedb.go
- core/test_blockchain.go
- internal/blocktest/test_hash.go
- internal/cmdtest/test_cmd.go
- params/config.go
- precompile/allowlist/test_allowlist.go
- precompile/allowlist/test_allowlist_config.go
- precompile/contract/test_utils.go
- precompile/testutils/test_config.go
- precompile/testutils/test_precompile.go
- precompile/testutils/test_predicate.go
- rpc/testservice_test.go
- scripts/build_test.sh
- scripts/run_ginkgo_load.sh
- scripts/run_ginkgo_precompile.sh
- scripts/run_ginkgo_warp.sh
- sync/handlers/test_providers.go
- sync/statesync/test_sync.go
- sync/syncutils/test_trie.go
- tests/rlp_test_util.go
- tests/state_test_util.go
- warp/warptest/block_client.go
> Update avalanchego x

- eth/tracers/api.go
- params/config.go
- params/config_extra.go
- params/network_upgrades.go
- params/network_upgrades_test.go
- plugin/evm/vm_test.go
- plugin/evm/vm_upgrade_bytes_test.go
> rename e upgrade to etna

- eth/filters/filter_system_test.go
- metrics/sample.go
- plugin/evm/vm.go
> chore: fix some function names

- .golangci.yml
- scripts/build_bench_precompiles.sh
> remove test tags

- internal/ethapi/transaction_args.go
since london is activated I think this makes no difference.
it looks like this upstream
> nit: reduce diff with upstream

- scripts/build_docker_image.sh
- scripts/versions.sh
> build_docker_image.sh: use AVALANCHEGO_NODE_IMAGE

- plugin/evm/gossiper_eth_gossiping_test.go
> properly check err in ut

- params/config.go
Adds a new line before AvalancheUpgrades
> add new line after timestamp hardforks

- consensus/dummy/dynamic_fees.go
- consensus/dummy/dynamic_fees_test.go
Fixes modified common.Big1
Failing regression UT: https://github.com/ava-labs/subnet-evm/actions/runs/10891704003/job/30223173856
> fix modifying common.Big1

- README.md
- compatibility.json
- plugin/evm/version.go
> prepare for release v0.6.10

- plugin/evm/block_test.go
- plugin/evm/syncervm_test.go
- plugin/evm/tx_gossip_test.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
- plugin/evm/vm_upgrade_bytes_test.go
> remove the noSkip flag

- accounts/abi/bind/util_test.go
- scripts/known_flakes.txt
Mirrors https://github.com/ava-labs/coreth/pull/670
> fix chainID in TestWaitDeployedCornerCases

- README.md
> docs(readme): fix build and tests workflow badge link

- core/state_processor.go
- core/state_processor_ext.go
- core/state_processor_ext_test.go
- core/state_processor_test.go
- Move our code from state_processor.go to state_processor_ext.go
- Move our code from state_processor_test.go to state_procesor_ext_test.go
- Slight modifications to state_processor.go to make it more alike geth master
> chore(core): split out code in state_processor.go and state_processor_test.go

- .github/workflows/bench.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
Updates deprecated ubuntu 20.04 version to 22.04
> update ubuntu 20.04 to 22.04

- .github/ISSUE_TEMPLATE/release_checklist.md
- README.md
- RELEASES.md
- compatibility.json
- plugin/evm/version.go
> bump version to v0.7.2

- precompile/allowlist/config.go
use slices.Equal to simplify code
> refactor: use slices.Equal to simplify code

- consensus/dummy/consensus.go
- core/chain_makers.go
- core/state_processor_test.go
- eth/api_backend.go
- eth/gasprice/gasprice_test.go
- miner/worker.go
- plugin/evm/gossip_test.go
- plugin/evm/header/base_fee.go
- plugin/evm/header/base_fee_test.go
- plugin/evm/header/block_gas_cost.go
- plugin/evm/header/block_gas_cost_test.go
- plugin/evm/header/dynamic_fee_windower.go
- plugin/evm/header/extra.go
- plugin/evm/header/extra_test.go
- plugin/evm/vm_test.go
- plugin/evm/vm_warp_test.go
- utils/denomination.go
Cherry picks following PR from Coreth
https://github.com/ava-labs/coreth/pull/816
https://github.com/ava-labs/coreth/pull/825
> Improve header tests

- consensus/dummy/consensus.go
- core/chain_makers.go
- miner/worker.go
- plugin/evm/header/block_gas_cost_test.go
- plugin/evm/header/gas_limit.go
- plugin/evm/header/gas_limit_test.go
- plugin/evm/upgrade/legacy/params.go
Cherry picks following PR from Coreth
https://github.com/ava-labs/coreth/pull/822
> Move `GasLimit` handling into the `header` package (#822)

- consensus/dummy/consensus.go
- core/test_blockchain.go
- eth/gasprice/fee_info_provider.go
- eth/gasprice/gasprice_test.go
- plugin/evm/header/block_gas_cost.go
- plugin/evm/header/block_gas_cost_test.go
Cherry picks following PRs from Coreth
https://github.com/ava-labs/coreth/pull/837
https://github.com/ava-labs/coreth/pull/840
https://github.com/ava-labs/coreth/pull/843
> Round up est fee

- core/evm.go
- core/test_blockchain.go
- core/vm/evm.go
- plugin/evm/block.go
- plugin/evm/header/extra.go
- plugin/evm/header/extra_test.go
- plugin/evm/vm_warp_test.go
- predicate/predicate_bytes.go
- predicate/predicate_bytes_test.go
Cherry picks following PRs from Coreth
https://github.com/ava-labs/coreth/pull/824
https://github.com/ava-labs/coreth/pull/845
> Predicate parsing refactor

- cmd/evm/internal/t8ntool/transition.go
- core/txpool/blobpool/blobpool_test.go
- plugin/evm/header/base_fee_test.go
- plugin/evm/header/dynamic_fee_windower.go
- plugin/evm/header/dynamic_fee_windower_test.go
- plugin/evm/header/extra.go
- plugin/evm/header/extra_test.go
- plugin/evm/upgrade/subnetevm/window.go
- plugin/evm/upgrade/subnetevm/window_test.go
Cherry picks following PRs from Coreth
https://github.com/ava-labs/coreth/pull/846
> Implement header.ExtraPrefix serialization in `upgrade/` packages (#846)

- consensus/dummy/consensus.go
- core/chain_makers.go
- core/state_processor_test.go
- eth/gasprice/gasprice_test.go
- miner/worker.go
- plugin/evm/header/block_gas_cost.go
- plugin/evm/header/block_gas_cost_test.go
- plugin/evm/header/extra.go
- plugin/evm/header/extra_test.go
- plugin/evm/header/gas_limit.go
- plugin/evm/header/gas_limit_test.go
Partially syncs https://github.com/ava-labs/coreth/pull/815 (without F-Upgrade/Acp176 stuff) and https://github.com/ava-labs/coreth/pull/849
> Header package refactor (continued)

- eth/gasprice/gasprice.go
Cherry-picks https://github.com/ava-labs/coreth/pull/865
> fix(eth/gasprice): EstimateBaseFee using Next Fee

- core/evm.go
- core/rawdb/accessors_metadata.go
- precompile/allowlist/allowlist.go
- sync/statesync/code_syncer.go
> chore: fix some typos in comment

- precompile/contracts/rewardmanager/contract.go
> chore: fix problematic comment

- plugin/evm/database/database.go
Mirrors https://github.com/ava-labs/avalanchego/pull/3892
> wrap corruptable db

- peer/network.go
- peer/network_test.go
- peer/peertest/request_id.go
- plugin/evm/message/request.go
- plugin/evm/vm_warp_test.go
Cherry picks https://github.com/ava-labs/coreth/pull/977
> remove request parse check in network forwarding (#977)

- plugin/evm/vm.go
- warp/aggregator/signature_getter.go
- warp/handlers/signature_request_test.go
- warp/service.go
Mirrors https://github.com/ava-labs/coreth/pull/961
> Refactor warp code (#961)

- plugin/evm/block_builder.go
- plugin/evm/vm.go
- plugin/evm/vm_warp_test.go
Syncs changes from coreth PR #967 https://github.com/ava-labs/coreth/pull/967/ (commit 38e0319f7c3c1451278017f01683fd02c0f231a9) to remove dead code and improve test organization.
> sync: coreth PR #967: remove dead code

- core/state/database.go
- core/state/database_test.go
- core/state/firewood_database.go
- go.mod
- go.sum
- latest-coreth-commit.txt
- plugin/evm/customrawdb/database_ext.go
- plugin/evm/customrawdb/schema_ext.go
- triedb/firewood/account_trie.go
- triedb/firewood/database.go
- triedb/firewood/storage_trie.go
Cherry-picks ava-labs/coreth#1029
> feat: Add Firewood Trie implementation

- plugin/evm/config/config.md
config file for remote content on builder hub
> feat: config.md

- plugin/evm/config/config.md
Updated documentation for state-history change.
> docs: add state-history

- latest-coreth-commit.txt
- triedb/firewood/database.go
Cherry-picks ava-labs/coreth#1071
> fix: remove firewood race

- latest-coreth-commit.txt
- sync/statesync/sync_test.go
Syncs https://github.com/ava-labs/coreth/pull/1062
> sync: coreth PR #1062: use require in statesync tests

- RELEASES.md
- latest-coreth-commit.txt
- plugin/evm/config/config.md
- plugin/evm/vm.go
- plugin/evm/vm_test.go
Syncs https://github.com/ava-labs/coreth/pull/1061
> sync: coreth PR #1061: firewood metrics

- latest-coreth-commit.txt
- plugin/evm/syncervm_client.go
- sync/statesync/state_syncer.go
- sync/statesync/sync_test.go
Syncs https://github.com/ava-labs/coreth/pull/1063
> sync: coreth PR #1063: change sync interface to Wait()

- core/state_transition.go
- go.mod
- go.sum
- latest-coreth-commit.txt
- params/hooks_libevm.go
Cherry-picks ava-labs/coreth#1087 and ava-labs/coreth#1088
> chore: update libevm version
